package com.atux.desktop.promocion;

import com.aw.swing.mvp.ui.GradientPanel;
import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by MATRIX-JAVA on 24/11/2014.
 */
public class FrmPromocionCrud {
    public JPanel pnlMain;
    public JTextField txtCoProducto;
    public JTextField txtDeProducto;
    public JTextField txtUnidadProducto;
    public JTextField txtCoProductoProv;
    public JTextField txtVaPrecioVenta;
    public JTextField txtCantidad;
    public JLabel lblCoProducto;
    public JLabel lblDeProducto;
    public JLabel lblUnidad;
    public JPanel pnlForm;
    public JPanel footerPanel;
    public JTextField txtVaFactor;
    public JLabel lblF10;
    public JLabel lblEsc;
    public JTextField txtDeLaboratorio;
    public JLabel lblLaboratorio;
    public JButton btnPickCoProducto;
    public JTextField txtInProdFraccionado;
    public JTextField txtVaFraccion;
    public JTextField txtUnidadFraccion;
    public JTextField txtCaEntero;
    public JTextField txtCaFraccion;
    public JTextField txtCaFraccionP;
    public JTextField txtCaEnteroP;
    public JTextField txtUnidadFraccionP;
    public JTextField txtVaFraccionP;
    public JTextField txtInProdFraccionadoP;
    public JLabel lblInProdFraccionadoP;
    public JLabel lblVaFraccionP;
    public JLabel lblUnidadFraccionP;
    public JLabel lblCaEnteroP;
    public JLabel lblCaFraccionP;
    public JTextField txtDeLaboratorioP;
    public JTextField txtUnidadProductoP;
    public JTextField txtDeProductoP;
    public JTextField txtCoProductoP;
    public JLabel lblDeLaboratorioP;
    public JLabel lblUnidadProductoP;
    public JLabel lblDeProductoP;
    public JLabel lblCoProductoP;
    public JLabel SepNuevo;
    public JLabel SepGratis;
    public JLabel lblCaFraccion;
    public JLabel lblCaEntero;
    public JLabel lblUnidadFraccion;
    public JLabel lblVaFraccion;
    public JLabel lblInProdFraccionado;
    public JButton btnPickCoProductoP;
    public JCheckBox chkIdemtico;
    public JLabel lblIdentico;

    private void createUIComponents() {
        pnlForm = new ZonePanel("Producto Promoción", true);
        footerPanel = new GradientPanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:d:noGrow,fill:d:grow,fill:d:noGrow", "fill:250dlu:noGrow,top:4dlu:noGrow,fill:16dlu:noGrow"));
        pnlMain.setMinimumSize(new Dimension(800, 452));
        pnlMain.setPreferredSize(new Dimension(800, 452));
        pnlForm.setLayout(new FormLayout("fill:103px:noGrow,left:4dlu:noGrow,fill:40dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:15dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:150dlu:noGrow", "center:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow"));
        pnlForm.setMinimumSize(new Dimension(540, 200));
        pnlForm.setPreferredSize(new Dimension(540, 200));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlForm, cc.xyw(1, 1, 3));
        lblDeProducto = new JLabel();
        lblDeProducto.setText("Producto");
        pnlForm.add(lblDeProducto, cc.xyw(3, 5, 3));
        txtCoProducto = new JTextField();
        pnlForm.add(txtCoProducto, cc.xy(1, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtDeProducto = new JTextField();
        pnlForm.add(txtDeProducto, cc.xyw(3, 7, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        btnPickCoProducto = new JButton();
        btnPickCoProducto.setIcon(new ImageIcon(getClass().getResource("/images/zoom.png")));
        btnPickCoProducto.setText("");
        pnlForm.add(btnPickCoProducto, cc.xy(9, 7));
        lblUnidad = new JLabel();
        lblUnidad.setText("Unidad");
        pnlForm.add(lblUnidad, cc.xy(11, 5));
        txtUnidadProducto = new JTextField();
        pnlForm.add(txtUnidadProducto, cc.xy(11, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblLaboratorio = new JLabel();
        lblLaboratorio.setText("Laboratorio");
        pnlForm.add(lblLaboratorio, cc.xy(13, 5));
        txtDeLaboratorio = new JTextField();
        pnlForm.add(txtDeLaboratorio, cc.xy(13, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblInProdFraccionado = new JLabel();
        lblInProdFraccionado.setText("Fraccionado");
        pnlForm.add(lblInProdFraccionado, cc.xy(1, 9));
        txtCaEntero = new JTextField();
        pnlForm.add(txtCaEntero, cc.xy(7, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtCaFraccion = new JTextField();
        pnlForm.add(txtCaFraccion, cc.xy(11, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtInProdFraccionado = new JTextField();
        pnlForm.add(txtInProdFraccionado, cc.xy(1, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtVaFraccion = new JTextField();
        pnlForm.add(txtVaFraccion, cc.xy(3, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtUnidadFraccion = new JTextField();
        pnlForm.add(txtUnidadFraccion, cc.xy(5, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblVaFraccion = new JLabel();
        lblVaFraccion.setText("Fracción");
        pnlForm.add(lblVaFraccion, cc.xy(3, 9));
        lblUnidadFraccion = new JLabel();
        lblUnidadFraccion.setText("Unidad Fracción");
        pnlForm.add(lblUnidadFraccion, cc.xy(5, 9));
        lblCaEntero = new JLabel();
        lblCaEntero.setText("Cant. Entero");
        pnlForm.add(lblCaEntero, cc.xy(7, 9));
        lblCaFraccion = new JLabel();
        lblCaFraccion.setText("Cant- Fracción");
        pnlForm.add(lblCaFraccion, cc.xy(11, 9));
        SepNuevo = new JLabel();
        SepNuevo.setText("Por la Compra De:");
        pnlForm.add(SepNuevo, cc.xy(1, 1));
        lblCoProducto = new JLabel();
        lblCoProducto.setText("Código");
        pnlForm.add(lblCoProducto, cc.xy(1, 17));
        lblCoProductoP = new JLabel();
        lblCoProductoP.setText("Código");
        pnlForm.add(lblCoProductoP, cc.xy(1, 5));
        lblDeProductoP = new JLabel();
        lblDeProductoP.setText("Producto");
        pnlForm.add(lblDeProductoP, cc.xyw(3, 17, 3));
        lblUnidadProductoP = new JLabel();
        lblUnidadProductoP.setText("Unidad");
        pnlForm.add(lblUnidadProductoP, cc.xy(11, 17));
        lblDeLaboratorioP = new JLabel();
        lblDeLaboratorioP.setText("Laboratorio");
        pnlForm.add(lblDeLaboratorioP, cc.xy(13, 17));
        txtCoProductoP = new JTextField();
        pnlForm.add(txtCoProductoP, cc.xy(1, 19, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtDeProductoP = new JTextField();
        pnlForm.add(txtDeProductoP, cc.xyw(3, 19, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtUnidadProductoP = new JTextField();
        pnlForm.add(txtUnidadProductoP, cc.xy(11, 19, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtDeLaboratorioP = new JTextField();
        pnlForm.add(txtDeLaboratorioP, cc.xy(13, 19, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblInProdFraccionadoP = new JLabel();
        lblInProdFraccionadoP.setText("Fraccionado");
        pnlForm.add(lblInProdFraccionadoP, cc.xy(1, 21));
        lblVaFraccionP = new JLabel();
        lblVaFraccionP.setText("Fracción");
        pnlForm.add(lblVaFraccionP, cc.xy(3, 21));
        lblUnidadFraccionP = new JLabel();
        lblUnidadFraccionP.setText("Unidad Fracción");
        pnlForm.add(lblUnidadFraccionP, cc.xy(5, 21));
        lblCaEnteroP = new JLabel();
        lblCaEnteroP.setText("Cant. Entero");
        pnlForm.add(lblCaEnteroP, cc.xy(7, 21));
        lblCaFraccionP = new JLabel();
        lblCaFraccionP.setText("Cant- Fracción");
        pnlForm.add(lblCaFraccionP, cc.xy(11, 21));
        txtInProdFraccionadoP = new JTextField();
        pnlForm.add(txtInProdFraccionadoP, cc.xy(1, 23, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtVaFraccionP = new JTextField();
        pnlForm.add(txtVaFraccionP, cc.xy(3, 23, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtUnidadFraccionP = new JTextField();
        pnlForm.add(txtUnidadFraccionP, cc.xy(5, 23, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtCaEnteroP = new JTextField();
        pnlForm.add(txtCaEnteroP, cc.xy(7, 23, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtCaFraccionP = new JTextField();
        pnlForm.add(txtCaFraccionP, cc.xy(11, 23, CellConstraints.FILL, CellConstraints.DEFAULT));
        SepGratis = new JLabel();
        SepGratis.setText("Lleve Gratis");
        pnlForm.add(SepGratis, cc.xy(1, 13));
        final JSeparator separator1 = new JSeparator();
        pnlForm.add(separator1, cc.xyw(1, 3, 13, CellConstraints.FILL, CellConstraints.FILL));
        final JSeparator separator2 = new JSeparator();
        pnlForm.add(separator2, cc.xyw(1, 15, 13, CellConstraints.FILL, CellConstraints.FILL));
        btnPickCoProductoP = new JButton();
        btnPickCoProductoP.setIcon(new ImageIcon(getClass().getResource("/images/zoom.png")));
        btnPickCoProductoP.setText("");
        pnlForm.add(btnPickCoProductoP, cc.xy(9, 19));
        lblIdentico = new JLabel();
        lblIdentico.setText("Identico");
        pnlForm.add(lblIdentico, cc.xy(7, 1));
        chkIdemtico = new JCheckBox();
        chkIdemtico.setText("");
        pnlForm.add(chkIdemtico, cc.xy(9, 1));
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,right:d:grow", "fill:16dlu:noGrow"));
        pnlMain.add(footerPanel, cc.xy(2, 3));
        lblF10 = new JLabel();
        lblF10.setText("F10 = Aceptar");
        footerPanel.add(lblF10, cc.xy(1, 1));
        lblEsc = new JLabel();
        lblEsc.setText("Esc = Cancelar");
        footerPanel.add(lblEsc, cc.xy(3, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
