package com.atux.desktop.comun.picks;

import com.aw.swing.mvp.ui.GradientPanel;
import com.aw.swing.mvp.ui.RoundedBorder;
import com.aw.swing.mvp.ui.RoundedPanel;
import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by MATRIX-JAVA on 27/11/2014.
 */
public class FrmPickUsuario {
    public JPanel pnlMain;
    public JPanel pnlForm;
    public JLabel lblIdUsuario;
    public JTextField txtIdUsuario;
    public JPanel pnlGrid;
    public JPanel pnlTitGrid;
    public JScrollPane pnlResult;
    public JTable tblGrid;
    public JCheckBox chkSel;
    public JLabel lblTitGrid;
    public JPanel footerPanel;
    public JLabel lblEnter;
    public JButton btnSearch;
    public JButton btnPickSelect;
    public JPanel pnlToolBarGrid;

    private void createUIComponents() {
        pnlForm = new ZonePanel("Usuarios", true);
        pnlGrid = new RoundedPanel(new BorderLayout(), 0);
        pnlGrid.setBorder(new RoundedBorder(0));
        pnlTitGrid = new GradientPanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:d:grow", "fill:d:grow,top:4dlu:noGrow,fill:170dlu:grow,top:4dlu:noGrow,fill:16dlu:noGrow"));
        pnlMain.setMinimumSize(new Dimension(600, 400));
        pnlMain.setPreferredSize(new Dimension(600, 400));
        pnlForm.setLayout(new FormLayout("fill:50dlu:noGrow,left:4dlu:noGrow,fill:60dlu:noGrow", "fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow"));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlForm, cc.xy(1, 1));
        lblIdUsuario = new JLabel();
        lblIdUsuario.setText("Usuario");
        pnlForm.add(lblIdUsuario, cc.xy(1, 1));
        txtIdUsuario = new JTextField();
        pnlForm.add(txtIdUsuario, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        btnSearch = new JButton();
        btnSearch.setText("Buscar");
        pnlForm.add(btnSearch, cc.xy(1, 3));
        pnlGrid.setLayout(new FormLayout("fill:d:grow", "fill:16dlu:noGrow,top:4dlu:noGrow,fill:14dlu:noGrow,top:4dlu:noGrow,fill:d:grow"));
        pnlMain.add(pnlGrid, cc.xy(1, 3));
        pnlTitGrid = new JPanel();
        pnlTitGrid.setLayout(new FormLayout("fill:16dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:16dlu:noGrow"));
        pnlGrid.add(pnlTitGrid, cc.xy(1, 1));
        chkSel = new JCheckBox();
        chkSel.setText("");
        pnlTitGrid.add(chkSel, cc.xy(1, 1));
        lblTitGrid = new JLabel();
        lblTitGrid.setText("Lista de usuarios");
        pnlTitGrid.add(lblTitGrid, cc.xy(3, 1));
        pnlResult = new JScrollPane();
        pnlGrid.add(pnlResult, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.FILL));
        tblGrid = new JTable();
        pnlResult.setViewportView(tblGrid);
        pnlToolBarGrid = new JPanel();
        pnlToolBarGrid.setLayout(new FormLayout("fill:d:noGrow", "fill:14dlu:noGrow"));
        pnlGrid.add(pnlToolBarGrid, cc.xy(1, 3));
        btnPickSelect = new JButton();
        btnPickSelect.setText("Seleccionar");
        pnlToolBarGrid.add(btnPickSelect, cc.xy(1, 1));
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("fill:d:grow", "center:d:grow,fill:16dlu:noGrow"));
        pnlMain.add(footerPanel, cc.xy(1, 5));
        lblEnter = new JLabel();
        lblEnter.setText("Enter = Seleccinar");
        footerPanel.add(lblEnter, cc.xy(1, 2));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
