/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Prueba.java
 *
 * Created on 03/12/2014, 06:01:51 PM
 */
package atux.vistas.venta.aperCierre;

import atux.controllers.CUsuario;
import atux.controllers.CObsCaja;
import atux.modelbd.ObsCaja;
import atux.modelbd.Usuario;
import atux.modelgui.ModeloTablaObsCierreCaja;
import atux.util.Helper;
import atux.util.common.AtuxSearch;
import atux.util.common.AtuxUtility;
import atux.util.common.AtuxVariables;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;


/**
 *
 * @author Omar Davila
 */
public class IObsCaja extends javax.swing.JDialog {
    private static Usuario usuario;
    private final Log logger = LogFactory.getLog(getClass());
    private ObsCaja obs;    
    private CObsCaja controllerObsCaja;
    private ModeloTablaObsCierreCaja mtped;
    private boolean CambioRealizado = false;
    private String titulo = "SA-VENTA";
    /** Creates new form Prueba */
    public IObsCaja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Limpiar();
        AtuxUtility.centrarVentana(this);
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagePrueba = new elaprendiz.gui.panel.PanelImage();
        jPanel2 = new javax.swing.JPanel();
        txtCaja = new elaprendiz.gui.textField.TextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFecha = new elaprendiz.gui.textField.TextField();
        txtTurno = new elaprendiz.gui.textField.TextField();
        jPanel3 = new javax.swing.JPanel();
        btnAgregar = new elaprendiz.gui.button.ButtonRound();
        btnEliminar = new elaprendiz.gui.button.ButtonRound();
        btnGuardar = new elaprendiz.gui.button.ButtonRound();
        btnEsc = new elaprendiz.gui.button.ButtonRound();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreCajero = new elaprendiz.gui.textField.TextField();
        txtCodCajero = new elaprendiz.gui.textField.TextField();
        jPanel1 = new javax.swing.JPanel();
        txtObs = new elaprendiz.gui.textField.TextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cierre Caja Turno");
        setResizable(false);

        panelImagePrueba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atux/resources/fondoazulceleste.jpg"))); // NOI18N

        jPanel2.setEnabled(false);
        jPanel2.setOpaque(false);

        txtCaja.setText("txtCaja");
        txtCaja.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCaja.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("Caja :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setText("Turno :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setText("Fecha :");

        txtFecha.setText("txtFecha");
        txtFecha.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFecha.setEnabled(false);

        txtTurno.setText("txtTurno");
        txtTurno.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTurno.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(txtCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8)
                .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setOpaque(false);

        btnAgregar.setMnemonic('A');
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setMnemonic('E');
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setMnemonic('A');
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEsc.setMnemonic('A');
        btnEsc.setText("Salir");
        btnEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEsc, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setFocusable(false);
        jPanel4.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Cajero :");

        txtNombreCajero.setEditable(false);
        txtNombreCajero.setText("txtNombreCajero");

        txtCodCajero.setEditable(false);
        txtCodCajero.setText("txtCodCajero");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreCajero, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(txtNombreCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtCodCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtObs.setText("txtObs");
        txtObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtObsKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Observación :");

        tblListado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblListado.setFont(new java.awt.Font("Tahoma", 0, 14));
        tblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orden", "Observación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListado.setGridColor(new java.awt.Color(0, 0, 0));
        tblListado.setRowHeight(22);
        tblListado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblListadoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblListado);
        tblListado.getColumnModel().getColumn(0).setPreferredWidth(100);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelImagePruebaLayout = new javax.swing.GroupLayout(panelImagePrueba);
        panelImagePrueba.setLayout(panelImagePruebaLayout);
        panelImagePruebaLayout.setHorizontalGroup(
            panelImagePruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagePruebaLayout.createSequentialGroup()
                .addGroup(panelImagePruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImagePruebaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelImagePruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelImagePruebaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelImagePruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelImagePruebaLayout.setVerticalGroup(
            panelImagePruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagePruebaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagePrueba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagePrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscActionPerformed
// TODO add your handling code here:
    Cerrar();
}//GEN-LAST:event_btnEscActionPerformed
private void Cerrar(){
    if (CambioRealizado == true){
        if (JOptionPane.showConfirmDialog(this, "Esta seguro de Salir sin Guardar", "Mensaje del Sistema", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION) {
            return;
        }
    }
    dispose();
}
private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    Agregar();
}//GEN-LAST:event_btnAgregarActionPerformed
private void Agregar(){
    if ("".equals(txtObs.getText().trim())){
        JOptionPane.showMessageDialog(this, "Debe de ingresar una observación");
        return;
    }
    CambioRealizado = true;
    obs = new ObsCaja();
    Date Fecha=FormatoFecha(txtFecha.getText());

    obs.setcoCompania(AtuxVariables.vCodigoCompania);
    obs.setcoLocal(AtuxVariables.vCodigoLocal);
    obs.setfeDiaVenta(Fecha);
    obs.setnuCaja(Integer.parseInt(txtCaja.getText()));
    obs.setnuTurno(Integer.parseInt(txtTurno.getText()));
    obs.setnuSecObs(tblListado.getRowCount() + 1);
    obs.setdeObs(txtObs.getText());

    mtped.agregarFila(obs);
    tblListado.repaint();
    mtped.fireTableDataChanged();
}

private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    EliminarRegistro();
}//GEN-LAST:event_btnEliminarActionPerformed
private void EliminarRegistro(){
    if (JOptionPane.showConfirmDialog(this, "Esta seguro de Eliminar el Registro", titulo, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION) {
        return;
    }

    obs = new ObsCaja();
    int Fila = tblListado.getSelectedRow();
    if (Fila==-1){
        JOptionPane.showMessageDialog(this, "Debe de seleccionar una fila");
        return;
    }
    CambioRealizado = true;
    mtped.quitarFila(Fila);
    tblListado.repaint();
    mtped.fireTableDataChanged();
}
        
private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    BotonGuardar();
}//GEN-LAST:event_btnGuardarActionPerformed
private void BotonGuardar(){
    if (JOptionPane.showConfirmDialog(this, "Esta seguro de Guardar los Datos", titulo, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION) {
        return;
    }

    try {
        guardar();
        AtuxUtility.aceptarTransaccion();
        CambioRealizado = false;
        JOptionPane.showMessageDialog(this, "Información Guardar satisfactoriamente");
    } catch (SQLException ex) {
        Logger.getLogger(IObsCaja.class.getName()).log(Level.SEVERE, null, ex);
    }
}
private void txtObsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObsKeyReleased
// TODO add your handling code here:
    switch (evt.getKeyCode()){
        case KeyEvent.VK_F2: Agregar();
             break;
        case KeyEvent.VK_F4: BotonGuardar();
             break;
        case KeyEvent.VK_ESCAPE: Cerrar();
             break;
    }
}//GEN-LAST:event_txtObsKeyReleased

private void tblListadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblListadoKeyReleased
// TODO add your handling code here:
    switch (evt.getKeyCode()){
        case KeyEvent.VK_F3: EliminarRegistro();
             break;
        case KeyEvent.VK_ESCAPE: Cerrar();
             break;
    }
}//GEN-LAST:event_tblListadoKeyReleased

private void guardar() throws SQLException{
    CObsCaja ObservacionCaja = new CObsCaja();
    String Data01 = ObservacionCaja.EliminaTodasObservaciones(AtuxVariables.vCodigoCompania, 
                                               AtuxVariables.vCodigoLocal, 
                                               txtFecha.getText(), 
                                               Integer.parseInt(txtCaja.getText()), 
                                               Integer.parseInt(txtTurno.getText()));
    
    if ("NoOk".equals(Data01)){
        JOptionPane.showMessageDialog(this, "Problemas al guardar Observaciones\n Favor Verifique");
        return;
    }

    obs = new ObsCaja();
    Date Fecha=FormatoFecha(txtFecha.getText());

    ModeloTablaObsCierreCaja caja = (ModeloTablaObsCierreCaja)tblListado.getModel();

    controllerObsCaja  = new CObsCaja();

    for (int j = 0; j<tblListado.getRowCount();  j++){
        obs =(ObsCaja)caja.getFila(j);

        obs.setcoCompania(AtuxVariables.vCodigoCompania);
        obs.setcoLocal(AtuxVariables.vCodigoLocal);
        obs.setfeDiaVenta(Fecha);
        obs.setnuCaja(Integer.parseInt(txtCaja.getText()));
        obs.setnuTurno(Integer.parseInt(txtTurno.getText()));
        obs.setnuSecObs(j + 1);
        obs.setidCreaObs(AtuxVariables.vIdUsuario );
        obs.setfeCreaObs(AtuxSearch.getFechaHora());
        boolean gr = controllerObsCaja.guardarRegistro(obs);    
    }
}

private Date FormatoFecha(String oldFecha){
    Date Fecha=null;
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
    String dateInString = oldFecha;

    try {
        Fecha = formatter.parse(dateInString);
    } catch (ParseException ex) {
        Logger.getLogger(IObsCaja.class.getName()).log(Level.SEVERE, null, ex);
    }
    return Fecha;
}

private void LeerObs(){
    CObsCaja ObservacionCaja = new CObsCaja();
    ArrayList Data01 = ObservacionCaja.LeerObservaciones(AtuxVariables.vCodigoCompania, 
                                               AtuxVariables.vCodigoLocal, 
                                               txtFecha.getText(), 
                                               Integer.parseInt(txtCaja.getText()), 
                                               Integer.parseInt(txtTurno.getText()));

    this.mtped = new ModeloTablaObsCierreCaja(Data01);
    tblListado.setModel(mtped);
    Helper.ajustarSoloAnchoColumnas(tblListado,ModeloTablaObsCierreCaja.anchoColumnas);   
    AtuxUtility.setearPrimerRegistro(tblListado, null, 0);
    AtuxUtility.moveFocus(txtObs);
}  

private void Limpiar(){
    txtCodCajero.setText("");
    txtNombreCajero.setText("");
    txtCaja.setText("");
    txtFecha.setText("");
    txtTurno.setText("");
    txtObs.setText("");
    for (int i = tblListado.getRowCount() -1; i >= 0; i--)     {   
        ((DefaultTableModel) tblListado.getModel()).removeRow(i);
    }    
}

public void LlenaDatosCajero(String IdUsuario){
    Limpiar();
    txtCodCajero.setText(AtuxUtility.completeWithSymbol(txtCodCajero.getText(), 6, "0", "I"));
    CUsuario cuser = new CUsuario();
    usuario = new Usuario();        
    usuario = cuser.getRegistroPorPk2(new Object[]{AtuxVariables.vCodigoCompania,AtuxVariables.vCodigoLocal,txtCodCajero.getText()});
    
    if (usuario != null){
        txtNombreCajero.setText(usuario.getNombreCompleto());
        try {
            if ("N".equals(AtuxSearch.getInCajaAbierta(AtuxSearch.getNuCaja(txtCodCajero.getText())))){
                JOptionPane.showMessageDialog(this, "No existe Caja abierta para este usuario");
                return;
            }
            txtNombreCajero.setText(usuario.getNombreCompleto());
            txtCaja.setText(AtuxSearch.getNuCaja(txtCodCajero.getText()));
            txtTurno.setText(AtuxSearch.getNuTurno(txtCaja.getText()));
            txtFecha.setText(AtuxSearch.getFeModCajaPago(txtCaja.getText(), txtTurno.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(IObsCaja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }else{
        JOptionPane.showMessageDialog(this, "Codigo de Trabajador no existe");
    }
    LeerObs();   
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IObsCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IObsCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IObsCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IObsCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                IObsCaja dialog = new IObsCaja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void closeWindow(boolean pAceptar) {              
        AtuxVariables.vAceptar = pAceptar;       
        this.setVisible(false);        
        this.dispose();
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private elaprendiz.gui.button.ButtonRound btnAgregar;
    private elaprendiz.gui.button.ButtonRound btnEliminar;
    private elaprendiz.gui.button.ButtonRound btnEsc;
    private elaprendiz.gui.button.ButtonRound btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private elaprendiz.gui.panel.PanelImage panelImagePrueba;
    private javax.swing.JTable tblListado;
    private elaprendiz.gui.textField.TextField txtCaja;
    private elaprendiz.gui.textField.TextField txtCodCajero;
    private elaprendiz.gui.textField.TextField txtFecha;
    private elaprendiz.gui.textField.TextField txtNombreCajero;
    private elaprendiz.gui.textField.TextField txtObs;
    private elaprendiz.gui.textField.TextField txtTurno;
    // End of variables declaration//GEN-END:variables
}
