package atux.vistas.venta.caja;

import atux.controllers.CPedidoVenta;
import atux.controllers.CSimpleModelo;
import atux.controllers.CUsuario;
import atux.modelbd.PedidoVenta;
import atux.modelgui.ModeloTablaSimple;
import atux.util.ECampos;
import atux.util.Helper;
import atux.util.common.AtuxDBUtility;
import atux.util.common.AtuxSearch;
import atux.util.common.AtuxUtility;
import atux.util.common.AtuxVariables;
import atux.vistas.buscar.JBuscarCliente;
import com.aw.core.util.StringUtils;
import com.aw.swing.mvp.navigation.AWWindowsManager;

import java.awt.*;
import java.awt.event.KeyEvent;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import java.sql.SQLException;
import java.util.Calendar;

/**
 *
 * @author user
 */
public class IPedidoACredito extends javax.swing.JDialog {

    private PedidoVenta pedido;
    CPedidoVenta cPedidoVenta;
    private ModeloTablaSimple mFormaPagoCred;
    private CSimpleModelo controllerFormaPagCre;
    private final Log logger = LogFactory.getLog(getClass());

    /** Creates new form IPedidoACredito */
    public IPedidoACredito(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(0);
        AtuxUtility.centrarVentana(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage = new elaprendiz.gui.panel.PanelImage();
        pnlCabecera = new javax.swing.JPanel();
        lblNumPedido = new javax.swing.JLabel();
        txtNumeroPedido = new elaprendiz.gui.textField.TextField();
        lblTotal = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtVendedor = new elaprendiz.gui.textField.TextField();
        txtDireccion = new elaprendiz.gui.textField.TextField();
        txtCliente = new elaprendiz.gui.textField.TextField();
        lblVendedor = new javax.swing.JLabel();
        lblCredito = new javax.swing.JLabel();
        txtCredito = new elaprendiz.gui.textField.TextField();
        txtTotal = new elaprendiz.gui.textField.TextField();
        lblRedondeo = new javax.swing.JLabel();
        txtFechaPedido = new elaprendiz.gui.textField.TextField();
        lblNuDoc = new javax.swing.JLabel();
        dcFechaPago = new com.toedter.calendar.JDateChooser();
        bntAgregar = new elaprendiz.gui.button.ButtonRect();
        pnlDetalle = new javax.swing.JPanel();
        jPanelTable = new javax.swing.JPanel();
        jScrollPaneDet = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        lblDetalle = new javax.swing.JLabel();
        bntCobrar = new elaprendiz.gui.button.ButtonRect();
        bntSalir = new elaprendiz.gui.button.ButtonRect();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atux/resources/fondoazulceleste.jpg"))); // NOI18N

        pnlCabecera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCabecera.setOpaque(false);

        lblNumPedido.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblNumPedido.setText("No. Pedido ");

        txtNumeroPedido.setFont(new java.awt.Font("Arial", 1, 13));
        txtNumeroPedido.setPreferredSize(new java.awt.Dimension(615, 22));

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblTotal.setText("TOTAL:");

        lblCliente.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblCliente.setText("Cliente");

        lblDireccion.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblDireccion.setText("Dirección");

        txtVendedor.setPreferredSize(new java.awt.Dimension(615, 22));

        txtDireccion.setPreferredSize(new java.awt.Dimension(615, 22));

        txtCliente.setPreferredSize(new java.awt.Dimension(615, 22));
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClienteKeyPressed(evt);
            }
        });

        lblVendedor.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblVendedor.setText("Vendedor");

        lblCredito.setFont(new java.awt.Font("Tahoma", 1, 13));
        lblCredito.setText("Crédito");

        txtCredito.setPreferredSize(new java.awt.Dimension(615, 22));

        txtTotal.setPreferredSize(new java.awt.Dimension(615, 22));

        lblRedondeo.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblRedondeo.setText("Fecha Pedido");

        txtFechaPedido.setFont(new java.awt.Font("Arial", 1, 13));
        txtFechaPedido.setPreferredSize(new java.awt.Dimension(615, 22));

        lblNuDoc.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblNuDoc.setText("Fecha de pago");

        dcFechaPago.setBackground(new java.awt.Color(0, 0, 0));
        dcFechaPago.setForeground(new java.awt.Color(255, 0, 0));
        dcFechaPago.setDate(Calendar.getInstance().getTime());
        dcFechaPago.setFont(new java.awt.Font("Tahoma", 1, 12));
        dcFechaPago.setPreferredSize(new java.awt.Dimension(120, 22));
        dcFechaPago.setRequestFocusEnabled(false);

        bntAgregar.setBackground(new java.awt.Color(51, 153, 255));
        bntAgregar.setForeground(new java.awt.Color(255, 255, 102));
        bntAgregar.setText("Agregar");
        bntAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCabeceraLayout = new javax.swing.GroupLayout(pnlCabecera);
        pnlCabecera.setLayout(pnlCabeceraLayout);
        pnlCabeceraLayout.setHorizontalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCabeceraLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblNuDoc)
                        .addGap(6, 6, 6)
                        .addComponent(dcFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDireccion)
                        .addGap(18, 18, 18)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCabeceraLayout.createSequentialGroup()
                        .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblRedondeo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblNumPedido)))
                        .addGap(3, 3, 3)
                        .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                                .addComponent(txtNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblVendedor)
                                .addGap(12, 12, 12)
                                .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                                .addComponent(txtFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCliente)
                                .addGap(33, 33, 33)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(lblCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(82, 82, 82))
        );
        pnlCabeceraLayout.setVerticalGroup(
                pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCabeceraLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnlCabeceraLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(lblNumPedido))
                                        .addComponent(lblVendedor)
                                        .addComponent(txtVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNumeroPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlCabeceraLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(pnlCabeceraLayout.createSequentialGroup()
                                                                .addGap(5, 5, 5)
                                                                .addComponent(lblRedondeo))
                                                        .addComponent(lblCliente)
                                                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblCredito)
                                                        .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pnlCabeceraLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(txtFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlCabeceraLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(pnlCabeceraLayout.createSequentialGroup()
                                                                .addGap(2, 2, 2)
                                                                .addComponent(lblNuDoc))
                                                        .addComponent(lblDireccion)
                                                        .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(bntAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(pnlCabeceraLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(dcFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pnlDetalle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlDetalle.setOpaque(false);

        jPanelTable.setOpaque(false);

        jScrollPaneDet.setPreferredSize(new java.awt.Dimension(452, 150));

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null}
                },
                new String[]{
                        "Nro Pedido", "Fecha pedido", "SubTotal", "Descuento", "IGV", "Total", "Fecha a pagar"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        tblDetalle.setRowHeight(24);
        jScrollPaneDet.setViewportView(tblDetalle);

        lblDetalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDetalle.setText("Pedidos a crédito :");

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(658, Short.MAX_VALUE))
            .addComponent(jScrollPaneDet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addComponent(lblDetalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDet, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelImageLayout = new javax.swing.GroupLayout(panelImage);
        panelImage.setLayout(panelImageLayout);
        panelImageLayout.setHorizontalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
            .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelImageLayout.setVerticalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageLayout.createSequentialGroup()
                .addComponent(pnlCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bntCobrar.setBackground(new java.awt.Color(51, 153, 255));
        bntCobrar.setForeground(new java.awt.Color(255, 255, 102));
        bntCobrar.setText("Cobrar");
        bntCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCobrarActionPerformed(evt);
            }
        });

        bntSalir.setBackground(new java.awt.Color(51, 153, 255));
        bntSalir.setForeground(new java.awt.Color(255, 255, 102));
        bntSalir.setText("Salir");
        bntSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(567, Short.MAX_VALUE)
                .addComponent(bntCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAgregarActionPerformed
        cPedidoVenta = new CPedidoVenta();
        pedido = cPedidoVenta.getFormaPago(pedido);
        try {
            pedido.getdPcred().setCoFormaPagoCredito(AtuxVariables.FORMA_PAGO_CREDITO);
            pedido.getdPcred().setNuItemFormaPago(1);
            pedido.getdPcred().setFePago(dcFechaPago.getCalendar().getTime());
            pedido.getdPcred().setDeVentaCredito("Pagar a 15 días");
            pedido.getdPcred().setVaSaldo(pedido.getdPcred().getImTotalPago());
            pedido.getdPcred().setImPago(0d);
            pedido.getdPcred().setImTotalPago(0d);
            pedido.getdPcred().setInPagoBono("N");
            pedido.getdPcred().setInAnulado("N");
            pedido.getdPcred().setIdCreaFormaPagoPedido(AtuxVariables.vIdUsuario);
            pedido.setTiPedido(AtuxVariables.TIPO_PEDIDO_CREDITO);
            AtuxSearch.updateTipoPedidoCredito(AtuxVariables.TIPO_PEDIDO_CREDITO,pedido.getNuPedido());
            cPedidoVenta.guardarPagoCredito(pedido);
            AtuxUtility.aceptarTransaccion();
            cargarFormaPagoCredito(pedido);
            closeWindow(true);
        } catch (SQLException e) {
            logger.error("Error al guardar la forma de pago a crédito " + e.getMessage());
        }

    }//GEN-LAST:event_bntAgregarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(tieneFormaPagoCredito()){
            txtNumeroPedido.setText(pedido.getNuPedido());
            txtFechaPedido.setText(AtuxUtility.getDateToString(pedido.getFePedido(), "dd/MM/yyyy"));
            try {
                this.dcFechaPago.setDate(AtuxUtility.getStringToDate(AtuxSearch.getFechaHoraParametroBD(AtuxVariables.FORMATO_FECHA, AtuxVariables.vDiasPagoCredito),"dd/MM/yyyy"));

            } catch (SQLException ex) {
                logger.error("Error al obtener el numero de dias de crédito" + ex.getMessage());
            }
            txtVendedor.setText(new CUsuario().getRegistroPorPk2(new Object[]{pedido.getCoCompania(),pedido.getCoLocal(),pedido.getCoVendedor()}).getNombreCompleto());
            txtCliente.setText(pedido.getNoImpresoComprobante());
            txtDireccion.setText(pedido.getDeDireccionCliente());
            txtTotal.setText(String.valueOf(montoTotalPedido()));
            txtCredito.setText(String.valueOf((pedido.getMontoCredito()==null)?montoFormaPagoCredito():pedido.getMontoCredito()));
            cargarFormaPagoCredito(pedido);
            dcFechaPago.requestFocus();
        }
        else{
            closeWindow(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void bntSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalirActionPerformed
        closeWindow(true);
    }//GEN-LAST:event_bntSalirActionPerformed

    private void bntCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCobrarActionPerformed
        logger.info("Muestra el pago del pedido");
        IPagoPedido iPagoPedido = new IPagoPedido(AWWindowsManager.instance().getFrame(), "Pago de pedido", true);
        pedido.setVaTotalPrecioVenta(Double.parseDouble(txtCredito.getText()));
        iPagoPedido.setPedido(pedido);
        iPagoPedido.setVisible(true);
        bntSalir.doClick();
    }//GEN-LAST:event_bntCobrarActionPerformed

    private void txtClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

         JBuscarCliente buscarCliente = new JBuscarCliente(1,this,true);
         buscarCliente.setVisible(true);

         if(buscarCliente.getCliente() != null){
             //setCliente((Cliente)buscarCliente.getCliente());          
         }
      }
    }//GEN-LAST:event_txtClienteKeyPressed

    public void cargarFormaPagoCredito(PedidoVenta pedido){
        controllerFormaPagCre = new CSimpleModelo();
        mFormaPagoCred =  new ModeloTablaSimple(controllerFormaPagCre.getRelacionDePedidosCredito(pedido),ModeloTablaSimple.LST_FORMA_PAGO_CREDITO);
        tblDetalle.setModel(mFormaPagoCred);
        Helper.ajustarSoloAnchoColumnasPedCredito(tblDetalle, ModeloTablaSimple.anchoColumnasFormaPagoPedCredito);
        AtuxUtility.setearPrimerRegistro(tblDetalle, null, 0);
        AtuxUtility.moveFocus(tblDetalle);
    }

    public void setPedido(PedidoVenta pedido) {
        this.pedido = pedido;
    }

    public void closeWindow(boolean pAceptar) {
        AtuxVariables.vAceptar = pAceptar;
        this.setVisible(false);
        this.dispose();
    }

    boolean tieneFormaPagoCredito(){
        String val = null;
        try {
            val = AtuxDBUtility.getValueAt("VTTX_FORMA_PAGO_PEDIDO",
                    " COUNT(1)",
                    " CO_COMPANIA  = '" + pedido.getCoCompania() + "'" +
                            " AND CO_LOCAL     = '" + pedido.getCoLocal() + "'" +
                            " AND NU_PEDIDO    = '" + pedido.getNuPedido() + "'" +
                            " AND CO_FORMA_PAGO= '" + AtuxVariables.FORMA_PAGO_CREDITO + "'");
        } catch (SQLException e) {
            logger.error("Error al obtener la forma de pago ");
        }
        if (Integer.parseInt(val)>0){
            return true;
        }
        return false;
    }

    String montoFormaPagoCredito(){
        String val = null;
        try {
            val = AtuxDBUtility.getValueAt("VTTX_FORMA_PAGO_PEDIDO",
                    " IM_PAGO",
                    " CO_COMPANIA  = '" + pedido.getCoCompania() + "'" +
                            " AND CO_LOCAL     = '" + pedido.getCoLocal() + "'" +
                            " AND NU_PEDIDO    = '" + pedido.getNuPedido() + "'" +
                            " AND CO_FORMA_PAGO= '" + AtuxVariables.FORMA_PAGO_CREDITO + "'");
        } catch (SQLException e) {
            logger.error("Error al obtener la forma de pago ");
        }

        return val;
    }

    String montoTotalPedido(){
        String val = null;
        try {
            val = AtuxDBUtility.getValueAt("VTTC_PEDIDO_VENTA  CAB",
                            "  (CAB.VA_TOTAL_VENTA        + \n" +
                            "   CAB.VA_TOTAL_IMPUESTO - \n" +
                            "   CAB.VA_TOTAL_DESCUENTO) \n" +
                            "   +\n" +
                            "   NVL((SELECT DON.VA_DONACION\n" +
                            "         FROM VTTR_PEDIDO_DONACION DON \n" +
                            "         WHERE DON.CO_COMPANIA= CAB.CO_COMPANIA\n" +
                            "           AND DON.CO_LOCAL   = CAB.CO_LOCAL\n" +
                            "           AND DON.NU_PEDIDO  = CAB.NU_PEDIDO),0) TOTAL",
                            " CO_COMPANIA   = '" + pedido.getCoCompania() + "'" +
                            " AND CO_LOCAL  = '" + pedido.getCoLocal()  + "'" +
                            " AND NU_PEDIDO = '" + pedido.getNuPedido() + "'");
        } catch (SQLException e) {
            logger.error("Error al obtener el total del pedido ");
        }

        return val;
    }

    public void setInactivaCabecera() {
        ECampos.setEditableTexto(this.pnlCabecera, false, new Component[]{lblNumPedido,lblVendedor,lblTotal,lblRedondeo,lblCliente,lblCredito,lblNuDoc,lblDireccion}, false, "");
        dcFechaPago.setDate(null);
        dcFechaPago.setEnabled(false);
        bntAgregar.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private elaprendiz.gui.button.ButtonRect bntAgregar;
    public elaprendiz.gui.button.ButtonRect bntCobrar;
    public elaprendiz.gui.button.ButtonRect bntSalir;
    private com.toedter.calendar.JDateChooser dcFechaPago;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JScrollPane jScrollPaneDet;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCredito;
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNuDoc;
    private javax.swing.JLabel lblNumPedido;
    private javax.swing.JLabel lblRedondeo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVendedor;
    private elaprendiz.gui.panel.PanelImage panelImage;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JTable tblDetalle;
    public elaprendiz.gui.textField.TextField txtCliente;
    private elaprendiz.gui.textField.TextField txtCredito;
    private elaprendiz.gui.textField.TextField txtDireccion;
    private elaprendiz.gui.textField.TextField txtFechaPedido;
    private elaprendiz.gui.textField.TextField txtNumeroPedido;
    private elaprendiz.gui.textField.TextField txtTotal;
    private elaprendiz.gui.textField.TextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
