package com.atux.desktop.precios;

import com.aw.swing.mvp.ui.GradientPanel;
import com.aw.swing.mvp.ui.RoundedBorder;
import com.aw.swing.mvp.ui.RoundedPanel;
import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by MATRIX-JAVA on 24/11/2014.
 */
public class FrmFNProveedorProducto {
    public JPanel pnlMain;
    public JPanel pnlGrid;
    public JPanel pnlTitGrid;
    public JScrollPane pnlResult;
    public JTable tblGrid;
    public JCheckBox chkSel;
    public JLabel lblTitGrid;
    public JPanel pnlGrid1;
    public JPanel pnlTitGrid1;
    public JCheckBox chkSel1;
    public JScrollPane pnlResult1;
    public JTable tblGrid1;
    public JLabel lblTitGrid1;
    public JPanel footerPanel;
    public JPanel pnlForm;
    public JLabel lblProveedor;
    public JTextField txtSearch;
    public JButton btnSearch;

    private void createUIComponents() {
        pnlForm = new ZonePanel("Proveedor", true);
        pnlGrid = new RoundedPanel(new BorderLayout(), 0);
        pnlGrid.setBorder(new RoundedBorder(0));
        pnlGrid1 = new RoundedPanel(new BorderLayout(), 0);
        pnlGrid1.setBorder(new RoundedBorder(0));
        footerPanel = new GradientPanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:d:grow", "fill:50dlu:grow,top:4dlu:noGrow,fill:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        pnlMain.setMinimumSize(new Dimension(800, 600));
        pnlMain.setPreferredSize(new Dimension(1000, 668));
        pnlGrid.setLayout(new FormLayout("fill:d:grow", "fill:16dlu:noGrow,top:4dlu:noGrow,fill:d:grow"));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlGrid, cc.xy(1, 3));
        pnlTitGrid = new JPanel();
        pnlTitGrid.setLayout(new FormLayout("fill:16dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:16dlu:noGrow"));
        pnlGrid.add(pnlTitGrid, cc.xy(1, 1));
        chkSel = new JCheckBox();
        chkSel.setText("");
        pnlTitGrid.add(chkSel, cc.xy(1, 1));
        lblTitGrid = new JLabel();
        lblTitGrid.setText("Lista de Proveedores");
        pnlTitGrid.add(lblTitGrid, cc.xy(3, 1));
        pnlResult = new JScrollPane();
        pnlGrid.add(pnlResult, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        tblGrid = new JTable();
        pnlResult.setViewportView(tblGrid);
        pnlGrid1.setLayout(new FormLayout("fill:d:grow", "fill:16dlu:noGrow,top:4dlu:noGrow,fill:d:noGrow"));
        pnlMain.add(pnlGrid1, cc.xy(1, 5));
        pnlTitGrid1 = new JPanel();
        pnlTitGrid1.setLayout(new FormLayout("fill:16dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:16dlu:noGrow"));
        pnlGrid1.add(pnlTitGrid1, cc.xy(1, 1));
        chkSel1 = new JCheckBox();
        chkSel1.setText("");
        pnlTitGrid1.add(chkSel1, cc.xy(1, 1));
        lblTitGrid1 = new JLabel();
        lblTitGrid1.setText("Lista de Productos");
        pnlTitGrid1.add(lblTitGrid1, cc.xy(3, 1));
        pnlResult1 = new JScrollPane();
        pnlGrid1.add(pnlResult1, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        tblGrid1 = new JTable();
        pnlResult1.setViewportView(tblGrid1);
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:16dlu:noGrow"));
        pnlMain.add(footerPanel, cc.xy(1, 7));
        final JLabel label1 = new JLabel();
        label1.setText("F2 = Modificar Precio/Dscto");
        footerPanel.add(label1, cc.xy(1, 1));
        final JLabel label2 = new JLabel();
        label2.setText("F4 = Consultar");
        footerPanel.add(label2, cc.xy(3, 1));
        pnlForm.setLayout(new FormLayout("fill:50dlu:noGrow,left:4dlu:noGrow,fill:100dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:12dlu:noGrow"));
        pnlMain.add(pnlForm, cc.xy(1, 1));
        lblProveedor = new JLabel();
        lblProveedor.setText("Proveedor");
        pnlForm.add(lblProveedor, cc.xy(1, 1));
        txtSearch = new JTextField();
        pnlForm.add(txtSearch, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        btnSearch = new JButton();
        btnSearch.setText("Buscar");
        pnlForm.add(btnSearch, cc.xy(5, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
