package com.atux.desktop.precios;

import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by MATRIX-JAVA on 24/11/2014.
 */
public class FrmIncentivoCrud {
    public JPanel pnlMain;
    public JTextField txtCoProducto;
    public JTextField txtDeProducto;
    public JLabel lblCoProducto;
    public JTextField txtUnidad;
    public JLabel lblDeProducto;
    public JLabel lblUnidad;
    public JTextField txtDeLaboratorio;
    public JLabel lblDeLaboratorio;
    public JTextField txtFeInicio;
    public JTextField txtFeFin;
    public JTextField txtVaIncentivo;
    public JTextField txtPrecioPromedio;
    public JTextField txtPrecioPVP;
    public JTextField txtPrecioVenta;
    public JTextField txtPrecioPVPFinal;
    public JTextField txtVaMargen;
    public JLabel lblFeInicio;
    public JLabel lblFeFin;
    public JLabel lblVaIncentivo;
    public JSeparator sep1;
    public JLabel lblVaPrecioPromedio;
    public JLabel lblVaPrecioPVP;
    public JLabel lblVaPrecioVenta;
    public JLabel lblVaPrecioPVPFinal;
    public JLabel lblVaMargen;
    public JTextField txtFeRegistro;
    public JTextField txtFeVigencia;
    public JLabel lblFechaRegistro;
    public JLabel lblF10;
    public JPanel footerPanel;
    public JPanel pnlForm;
    public JLabel lblEsc;

    private void createUIComponents() {
        pnlForm = new ZonePanel("Crear Incentivo", true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:d:grow", "fill:d:grow,top:4dlu:noGrow,fill:16dlu:noGrow"));
        pnlMain.setMinimumSize(new Dimension(508, 370));
        pnlMain.setPreferredSize(new Dimension(508, 370));
        pnlForm.setLayout(new FormLayout("fill:45dlu:noGrow,left:4dlu:noGrow,fill:45dlu:noGrow,left:4dlu:noGrow,fill:45dlu:noGrow,left:4dlu:noGrow,fill:45dlu:noGrow,left:4dlu:noGrow,fill:45dlu:noGrow,left:4dlu:noGrow,fill:20dlu:noGrow", "fill:12dlu:noGrow,fill:4dlu:noGrow,fill:12dlu:noGrow,fill:4dlu:noGrow,fill:12dlu:noGrow,fill:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow"));
        pnlForm.setMinimumSize(new Dimension(400, 244));
        pnlForm.setPreferredSize(new Dimension(400, 244));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlForm, cc.xy(1, 1));
        lblCoProducto = new JLabel();
        lblCoProducto.setText("Código");
        pnlForm.add(lblCoProducto, cc.xy(1, 1));
        txtCoProducto = new JTextField();
        txtCoProducto.setText("");
        pnlForm.add(txtCoProducto, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblDeProducto = new JLabel();
        lblDeProducto.setText("Producto");
        pnlForm.add(lblDeProducto, cc.xyw(3, 1, 3));
        txtDeProducto = new JTextField();
        pnlForm.add(txtDeProducto, cc.xyw(3, 3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblUnidad = new JLabel();
        lblUnidad.setText("Unidad");
        pnlForm.add(lblUnidad, cc.xy(7, 1));
        txtUnidad = new JTextField();
        pnlForm.add(txtUnidad, cc.xy(7, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblDeLaboratorio = new JLabel();
        lblDeLaboratorio.setText("Laboratorio");
        pnlForm.add(lblDeLaboratorio, cc.xy(1, 5));
        txtDeLaboratorio = new JTextField();
        pnlForm.add(txtDeLaboratorio, cc.xyw(1, 7, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        sep1 = new JSeparator();
        pnlForm.add(sep1, cc.xyw(1, 9, 7, CellConstraints.FILL, CellConstraints.FILL));
        lblFeInicio = new JLabel();
        lblFeInicio.setText("Fecha Inicio");
        pnlForm.add(lblFeInicio, cc.xy(1, 13));
        txtVaMargen = new JTextField();
        pnlForm.add(txtVaMargen, cc.xy(9, 21, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtPrecioPVPFinal = new JTextField();
        pnlForm.add(txtPrecioPVPFinal, cc.xy(7, 21, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtPrecioPromedio = new JTextField();
        pnlForm.add(txtPrecioPromedio, cc.xy(1, 21, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblFeFin = new JLabel();
        lblFeFin.setText("Fecha Termino");
        pnlForm.add(lblFeFin, cc.xy(5, 13));
        txtFeInicio = new JTextField();
        pnlForm.add(txtFeInicio, cc.xy(3, 13, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtFeFin = new JTextField();
        pnlForm.add(txtFeFin, cc.xy(7, 13, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblVaIncentivo = new JLabel();
        lblVaIncentivo.setHorizontalAlignment(4);
        lblVaIncentivo.setText("Monto de Incentivo : S/.");
        pnlForm.add(lblVaIncentivo, cc.xyw(1, 15, 3));
        lblVaMargen = new JLabel();
        lblVaMargen.setText("Margen %");
        pnlForm.add(lblVaMargen, cc.xy(9, 19));
        lblVaPrecioPVPFinal = new JLabel();
        lblVaPrecioPVPFinal.setText("PVP. Final");
        pnlForm.add(lblVaPrecioPVPFinal, cc.xy(7, 19));
        lblVaPrecioVenta = new JLabel();
        lblVaPrecioVenta.setText("Precio Vta.");
        pnlForm.add(lblVaPrecioVenta, cc.xy(5, 19));
        lblVaPrecioPVP = new JLabel();
        lblVaPrecioPVP.setText("PVP. S/ IGV");
        pnlForm.add(lblVaPrecioPVP, cc.xy(3, 19));
        lblVaPrecioPromedio = new JLabel();
        lblVaPrecioPromedio.setText("Precio Prom.");
        pnlForm.add(lblVaPrecioPromedio, cc.xy(1, 19));
        final JSeparator separator1 = new JSeparator();
        pnlForm.add(separator1, cc.xyw(1, 17, 7, CellConstraints.FILL, CellConstraints.FILL));
        txtVaIncentivo = new JTextField();
        pnlForm.add(txtVaIncentivo, cc.xy(5, 15, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtPrecioVenta = new JTextField();
        pnlForm.add(txtPrecioVenta, cc.xy(5, 21, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtPrecioPVP = new JTextField();
        pnlForm.add(txtPrecioPVP, cc.xy(3, 21, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblFechaRegistro = new JLabel();
        lblFechaRegistro.setHorizontalAlignment(2);
        lblFechaRegistro.setText("Fecha Registro");
        pnlForm.add(lblFechaRegistro, cc.xy(1, 11));
        txtFeRegistro = new JTextField();
        pnlForm.add(txtFeRegistro, cc.xyw(3, 11, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,right:d:grow", "fill:d:grow"));
        pnlMain.add(footerPanel, cc.xy(1, 3));
        lblF10 = new JLabel();
        lblF10.setText("F10 = Aceptar");
        footerPanel.add(lblF10, cc.xy(1, 1));
        lblEsc = new JLabel();
        lblEsc.setText("Esc = Salir");
        footerPanel.add(lblEsc, cc.xy(3, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
