package com.atux.desktop.precios;

import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by MATRIX-JAVA on 24/11/2014.
 */
public class FrmMinExhibicionCrud {
    public JPanel pnlMain;
    public JTextField txtCoProducto;
    public JTextField txtDeProducto;
    public JLabel lblCoProducto;
    public JTextField txtUnidad;
    public JLabel lblDeProducto;
    public JLabel lblUnidad;
    public JTextField txtDeLaboratorio;
    public JLabel lblDeLaboratorio;
    public JTextField txtVaExhibicion;
    public JTextField txtPrecioPromedio;
    public JTextField txtPrecioPVP;
    public JTextField txtPrecioVenta;
    public JTextField txtPrecioPVPFinal;
    public JTextField txtVaMargen;
    public JLabel lblVaExhibicion;
    public JSeparator sep1;
    public JLabel lblVaPrecioPromedio;
    public JLabel lblVaPrecioPVP;
    public JLabel lblVaPrecioVenta;
    public JLabel lblVaPrecioPVPFinal;
    public JLabel lblVaMargen;
    public JPanel footerPanel;
    public JLabel lblF10;
    public JPanel pnlForm;
    public JLabel lblEsc;

    private void createUIComponents() {
        pnlForm = new ZonePanel("Minimo Exhibición", true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:d:grow", "fill:d:grow,top:4dlu:noGrow,fill:16dlu:noGrow"));
        pnlMain.setMinimumSize(new Dimension(560, 310));
        pnlMain.setPreferredSize(new Dimension(560, 310));
        pnlMain.setRequestFocusEnabled(true);
        pnlForm.setLayout(new FormLayout("fill:50dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:20dlu:noGrow", "fill:12dlu:noGrow,fill:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow"));
        pnlForm.setMinimumSize(new Dimension(400, 244));
        pnlForm.setPreferredSize(new Dimension(400, 244));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlForm, cc.xy(1, 1));
        lblCoProducto = new JLabel();
        lblCoProducto.setText("Código");
        pnlForm.add(lblCoProducto, cc.xy(1, 1));
        lblDeProducto = new JLabel();
        lblDeProducto.setText("Producto");
        pnlForm.add(lblDeProducto, cc.xyw(3, 1, 3));
        txtCoProducto = new JTextField();
        txtCoProducto.setText("");
        pnlForm.add(txtCoProducto, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtDeProducto = new JTextField();
        pnlForm.add(txtDeProducto, cc.xyw(3, 3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblUnidad = new JLabel();
        lblUnidad.setText("Unidad");
        pnlForm.add(lblUnidad, cc.xy(7, 1));
        txtUnidad = new JTextField();
        pnlForm.add(txtUnidad, cc.xy(7, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblDeLaboratorio = new JLabel();
        lblDeLaboratorio.setText("Laboratorio");
        pnlForm.add(lblDeLaboratorio, cc.xy(1, 5));
        txtDeLaboratorio = new JTextField();
        pnlForm.add(txtDeLaboratorio, cc.xyw(1, 7, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JSeparator separator1 = new JSeparator();
        pnlForm.add(separator1, cc.xyw(1, 9, 7, CellConstraints.FILL, CellConstraints.FILL));
        lblVaExhibicion = new JLabel();
        lblVaExhibicion.setText("Cantidad - Min Exhibición");
        pnlForm.add(lblVaExhibicion, cc.xyw(1, 11, 3));
        txtVaExhibicion = new JTextField();
        pnlForm.add(txtVaExhibicion, cc.xy(5, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        sep1 = new JSeparator();
        pnlForm.add(sep1, cc.xyw(1, 13, 7, CellConstraints.FILL, CellConstraints.FILL));
        txtPrecioPromedio = new JTextField();
        pnlForm.add(txtPrecioPromedio, cc.xy(1, 17, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblVaPrecioPromedio = new JLabel();
        lblVaPrecioPromedio.setText("Precio Promedio");
        pnlForm.add(lblVaPrecioPromedio, cc.xy(1, 15));
        lblVaPrecioPVP = new JLabel();
        lblVaPrecioPVP.setText("PVP. S/ IGV");
        pnlForm.add(lblVaPrecioPVP, cc.xy(3, 15));
        lblVaPrecioVenta = new JLabel();
        lblVaPrecioVenta.setText("Precio Vta.");
        pnlForm.add(lblVaPrecioVenta, cc.xy(5, 15));
        lblVaPrecioPVPFinal = new JLabel();
        lblVaPrecioPVPFinal.setText("PVP. Final");
        pnlForm.add(lblVaPrecioPVPFinal, cc.xy(7, 15));
        lblVaMargen = new JLabel();
        lblVaMargen.setText("Margen %");
        pnlForm.add(lblVaMargen, cc.xy(9, 15));
        txtPrecioVenta = new JTextField();
        pnlForm.add(txtPrecioVenta, cc.xy(5, 17, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtPrecioPVP = new JTextField();
        pnlForm.add(txtPrecioPVP, cc.xy(3, 17, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtPrecioPVPFinal = new JTextField();
        pnlForm.add(txtPrecioPVPFinal, cc.xy(7, 17, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtVaMargen = new JTextField();
        pnlForm.add(txtVaMargen, cc.xy(9, 17, CellConstraints.FILL, CellConstraints.DEFAULT));
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,right:d:grow", "fill:16dlu:noGrow"));
        pnlMain.add(footerPanel, cc.xy(1, 3));
        lblF10 = new JLabel();
        lblF10.setText("F10 = Aceptar");
        footerPanel.add(lblF10, cc.xy(1, 1));
        lblEsc = new JLabel();
        lblEsc.setText("Esc = Cancelar");
        footerPanel.add(lblEsc, cc.xy(3, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
