package com.atux.desktop.precios;

import com.aw.swing.mvp.ui.GradientPanel;
import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by MATRIX-JAVA on 24/11/2014.
 */
public class FrmProveedorPrecioCrud {
    public JPanel pnlMain;
    public JTextField txtCoProducto;
    public JTextField txtDeProducto;
    public JTextField txtUnidad;
    public JTextField txtCoProductoProv;
    public JTextField txtVaPrecioVenta;
    public JTextField txtCantidad;
    public JLabel lblMoneda;
    public JLabel lblPorcentajeDescuento;
    public JLabel lblCoProducto;
    public JLabel lblDeProducto;
    public JLabel lblUnidad;
    public JPanel pnlForm;
    public JPanel footerPanel;
    public JTextField txtVaFactor;
    public JLabel lblPrecioProveedor;
    public JLabel lblF10;
    public JLabel lblEsc;
    public JTextField txtDeLaboratorio;
    public JLabel lblLaboratorio;
    public JButton btnPickCoProducto;

    private void createUIComponents() {
        pnlForm = new ZonePanel("Modificar Descuento / Precio Venta", true);
        footerPanel = new GradientPanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:d:noGrow,fill:d:grow,fill:d:noGrow", "fill:120dlu:noGrow,top:4dlu:noGrow,fill:16dlu:noGrow"));
        pnlMain.setMinimumSize(new Dimension(600, 252));
        pnlMain.setPreferredSize(new Dimension(600, 252));
        pnlForm.setLayout(new FormLayout("fill:103px:noGrow,left:4dlu:noGrow,fill:40dlu:noGrow,left:4dlu:noGrow,fill:40dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:15dlu:noGrow", "fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow"));
        pnlForm.setMinimumSize(new Dimension(540, 200));
        pnlForm.setPreferredSize(new Dimension(540, 200));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlForm, cc.xyw(1, 1, 3));
        lblCoProducto = new JLabel();
        lblCoProducto.setText("Código");
        pnlForm.add(lblCoProducto, cc.xy(1, 1));
        lblDeProducto = new JLabel();
        lblDeProducto.setText("Producto");
        pnlForm.add(lblDeProducto, cc.xyw(3, 1, 3));
        txtCoProducto = new JTextField();
        pnlForm.add(txtCoProducto, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtDeProducto = new JTextField();
        pnlForm.add(txtDeProducto, cc.xyw(3, 3, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblMoneda = new JLabel();
        lblMoneda.setText("Código Prod Prov");
        pnlForm.add(lblMoneda, cc.xy(1, 9));
        txtCoProductoProv = new JTextField();
        pnlForm.add(txtCoProductoProv, cc.xy(1, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtVaPrecioVenta = new JTextField();
        txtVaPrecioVenta.setText("");
        pnlForm.add(txtVaPrecioVenta, cc.xy(3, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblPrecioProveedor = new JLabel();
        lblPrecioProveedor.setText("Precio");
        pnlForm.add(lblPrecioProveedor, cc.xy(3, 9));
        lblPorcentajeDescuento = new JLabel();
        lblPorcentajeDescuento.setText("Cantidad");
        pnlForm.add(lblPorcentajeDescuento, cc.xy(5, 9));
        txtCantidad = new JTextField();
        pnlForm.add(txtCantidad, cc.xy(5, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblUnidad = new JLabel();
        lblUnidad.setText("Unidad");
        pnlForm.add(lblUnidad, cc.xy(1, 5));
        txtUnidad = new JTextField();
        pnlForm.add(txtUnidad, cc.xy(1, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblLaboratorio = new JLabel();
        lblLaboratorio.setText("Laboratorio");
        pnlForm.add(lblLaboratorio, cc.xy(3, 5));
        txtDeLaboratorio = new JTextField();
        pnlForm.add(txtDeLaboratorio, cc.xyw(3, 7, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        btnPickCoProducto = new JButton();
        btnPickCoProducto.setIcon(new ImageIcon(getClass().getResource("/images/zoom.png")));
        btnPickCoProducto.setText("");
        pnlForm.add(btnPickCoProducto, cc.xy(9, 3));
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,right:d:grow", "fill:16dlu:noGrow"));
        pnlMain.add(footerPanel, cc.xy(2, 3));
        lblF10 = new JLabel();
        lblF10.setText("F10 = Aceptar");
        footerPanel.add(lblF10, cc.xy(1, 1));
        lblEsc = new JLabel();
        lblEsc.setText("Esc = Cancelar");
        footerPanel.add(lblEsc, cc.xy(3, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
