package com.atux.desktop.inventario;

import com.aw.swing.mvp.ui.GradientPanel;
import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by JAVA on 30/11/2014.
 */
public class FrmAjusteStock {
    public JPanel pnlMain;
    public JPanel pnlForm;
    public JLabel lblCoProducto;
    public JTextField txtCoProducto;
    public JTextField txtDeProducto;
    public JTextField txtUnidad;
    public JTextField txtDeLaboratorio;
    public JTextField txtStkEntero;
    public JTextField txtStkFraccion;
    public JTextField txtPrecioPromedio;
    public JComboBox cmbCoMotivo;
    public JTextArea txtJustificacion;
    public JLabel lblDeProducto;
    public JLabel lblUnidad;
    public JLabel lblLaboratorio;
    public JLabel lblStkEntero;
    public JLabel lblStkFraccion;
    public JLabel lblPrecioPromedio;
    public JLabel lblMotivo;
    public JLabel lblJustificacion;
    public JPanel footerPanel;
    public JLabel lblF10;
    public JLabel lblEsc;

    private void createUIComponents() {
        // TODO: place custom component creation code here
        pnlForm = new ZonePanel("Ajuste de Stock", true);
        footerPanel = new GradientPanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:d:grow", "fill:d:grow,fill:4dlu:noGrow,fill:16dlu:noGrow"));
        pnlMain.setMinimumSize(new Dimension(664, 312));
        pnlMain.setPreferredSize(new Dimension(664, 312));
        pnlForm.setLayout(new FormLayout("fill:50dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:60dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:12dlu:noGrow,fill:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow"));
        pnlForm.setMinimumSize(new Dimension(554, 162));
        pnlForm.setPreferredSize(new Dimension(554, 162));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlForm, cc.xy(1, 1));
        lblCoProducto = new JLabel();
        lblCoProducto.setText("Código");
        pnlForm.add(lblCoProducto, cc.xy(1, 1));
        txtCoProducto = new JTextField();
        pnlForm.add(txtCoProducto, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblDeProducto = new JLabel();
        lblDeProducto.setText("Descripción");
        pnlForm.add(lblDeProducto, cc.xyw(3, 1, 3));
        txtDeProducto = new JTextField();
        pnlForm.add(txtDeProducto, cc.xyw(3, 3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblUnidad = new JLabel();
        lblUnidad.setText("Unidad");
        pnlForm.add(lblUnidad, cc.xy(7, 1));
        txtUnidad = new JTextField();
        pnlForm.add(txtUnidad, cc.xy(7, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblLaboratorio = new JLabel();
        lblLaboratorio.setText("Laboratorio");
        pnlForm.add(lblLaboratorio, cc.xy(9, 1));
        txtDeLaboratorio = new JTextField();
        pnlForm.add(txtDeLaboratorio, cc.xy(9, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblStkEntero = new JLabel();
        lblStkEntero.setText("Cant. Entera");
        pnlForm.add(lblStkEntero, cc.xy(1, 5));
        txtStkEntero = new JTextField();
        pnlForm.add(txtStkEntero, cc.xy(1, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblStkFraccion = new JLabel();
        lblStkFraccion.setText("Cant. Fracción");
        pnlForm.add(lblStkFraccion, cc.xy(3, 5));
        txtStkFraccion = new JTextField();
        pnlForm.add(txtStkFraccion, cc.xy(3, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblPrecioPromedio = new JLabel();
        lblPrecioPromedio.setText("Precio Promedio");
        pnlForm.add(lblPrecioPromedio, cc.xy(5, 5));
        txtPrecioPromedio = new JTextField();
        pnlForm.add(txtPrecioPromedio, cc.xy(5, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblMotivo = new JLabel();
        lblMotivo.setText("Motivo Ajuste");
        pnlForm.add(lblMotivo, cc.xy(7, 5));
        cmbCoMotivo = new JComboBox();
        pnlForm.add(cmbCoMotivo, cc.xyw(7, 7, 3));
        lblJustificacion = new JLabel();
        lblJustificacion.setText("Justificación de Ajuste de Stock");
        pnlForm.add(lblJustificacion, cc.xyw(1, 9, 3));
        txtJustificacion = new JTextArea();
        pnlForm.add(txtJustificacion, cc.xywh(1, 11, 7, 3, CellConstraints.FILL, CellConstraints.FILL));
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,right:d:grow", "center:d:grow"));
        pnlMain.add(footerPanel, cc.xy(1, 3));
        lblF10 = new JLabel();
        lblF10.setText("F10 = Aceptar");
        footerPanel.add(lblF10, cc.xy(1, 1));
        lblEsc = new JLabel();
        lblEsc.setText("Esc = Cancelar");
        footerPanel.add(lblEsc, cc.xy(3, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
