package com.atux.desktop.inventario;

import com.aw.swing.mvp.ui.GradientPanel;
import com.aw.swing.mvp.ui.RoundedBorder;
import com.aw.swing.mvp.ui.RoundedPanel;
import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by MATRIX-JAVA on 09/12/2014.
 */
public class FrmFNRotacion {
    public JPanel pnlMain;
    public JPanel pnlForm;
    public JPanel pnlGrid;
    public JPanel pnlTitGrid;
    public JScrollPane pnlResult;
    public JTable tblGrid;
    public JCheckBox chkSel;
    public JLabel lblTitGrid;
    public JLabel lblBuscar;
    public JTextField txtBuscar;
    public JPanel pnlGrid1;
    public JTable tblGrid1;
    public JCheckBox chkSel1;
    public JCheckBox chkSel2;
    public JTable tblGrid2;
    public JPanel pnlGrid2;
    public JPanel pnlTitGrid2;
    public JScrollPane pnlResult2;
    public JLabel lblTitGrid1;
    public JPanel pnlTitGrid1;
    public JScrollPane pnlResult1;
    public JLabel lblTitGrid2;
    public JPanel footerPanel;
    public JLabel lblEsc;
    public JButton btnSearch;
    public JTable tblGrid3;
    public JPanel pnlGrid3;
    public JPanel pnlTitGrid3;
    public JScrollPane pnlResult3;
    public JCheckBox chkSel3;
    public JLabel lblTitGrid3;
    public JPanel pnlGrid4;
    public JTable tblGrid4;
    public JCheckBox chkSel4;
    public JPanel pnlTitGrid4;
    public JScrollPane pnlResult4;
    public JLabel lblTitGrid4;

    private void createUIComponents() {
        pnlForm = new ZonePanel("Rotación de Productos", true);
        pnlGrid = new RoundedPanel(new BorderLayout(), 0);
        pnlGrid.setBorder(new RoundedBorder(0));
        pnlGrid1 = new RoundedPanel(new BorderLayout(), 0);
        pnlGrid1.setBorder(new RoundedBorder(0));
        pnlGrid2 = new RoundedPanel(new BorderLayout(), 0);
        pnlGrid2.setBorder(new RoundedBorder(0));
        pnlGrid3 = new RoundedPanel(new BorderLayout(), 0);
        pnlGrid3.setBorder(new RoundedBorder(0));

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:230dlu:noGrow,left:4dlu:noGrow,fill:230dlu:noGrow", "fill:36dlu:noGrow,top:4dlu:noGrow,fill:90dlu:noGrow,top:4dlu:noGrow,fill:84dlu:noGrow,top:4dlu:noGrow,fill:84dlu:noGrow,top:4dlu:noGrow,fill:16dlu:noGrow"));
        pnlMain.setMinimumSize(new Dimension(950, 528));
        pnlMain.setPreferredSize(new Dimension(950, 528));
        pnlForm.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow", "fill:12dlu:noGrow"));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlForm, cc.xyw(1, 1, 3));
        lblBuscar = new JLabel();
        lblBuscar.setText("Producto");
        pnlForm.add(lblBuscar, cc.xy(1, 1));
        txtBuscar = new JTextField();
        pnlForm.add(txtBuscar, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        btnSearch = new JButton();
        btnSearch.setText("Buscar");
        pnlForm.add(btnSearch, cc.xy(5, 1));
        pnlGrid.setLayout(new FormLayout("fill:d:grow", "fill:16dlu:noGrow,top:4dlu:noGrow,center:d:grow"));
        pnlGrid.setPreferredSize(new Dimension(454, 280));
        pnlMain.add(pnlGrid, cc.xyw(1, 3, 3));
        pnlTitGrid = new JPanel();
        pnlTitGrid.setLayout(new FormLayout("fill:16dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:d:noGrow"));
        pnlGrid.add(pnlTitGrid, cc.xy(1, 1));
        chkSel = new JCheckBox();
        chkSel.setText("");
        pnlTitGrid.add(chkSel, cc.xy(1, 1));
        lblTitGrid = new JLabel();
        lblTitGrid.setText("Lista de Productos");
        pnlTitGrid.add(lblTitGrid, cc.xy(3, 1));
        pnlResult = new JScrollPane();
        pnlResult.setPreferredSize(new Dimension(454, 280));
        pnlGrid.add(pnlResult, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        tblGrid = new JTable();
        pnlResult.setViewportView(tblGrid);
        pnlGrid1.setLayout(new FormLayout("fill:200dlu:grow", "center:d:noGrow,top:4dlu:noGrow,center:d:grow"));
        pnlGrid1.setMinimumSize(new Dimension(238, 55));
        pnlGrid1.setPreferredSize(new Dimension(238, 450));
        pnlMain.add(pnlGrid1, cc.xy(1, 7));
        pnlTitGrid1 = new JPanel();
        pnlTitGrid1.setLayout(new FormLayout("fill:16dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "center:d:noGrow"));
        pnlGrid1.add(pnlTitGrid1, cc.xy(1, 1));
        chkSel1 = new JCheckBox();
        chkSel1.setText("");
        pnlTitGrid1.add(chkSel1, cc.xy(1, 1));
        lblTitGrid1 = new JLabel();
        lblTitGrid1.setText("Valores de Venta en el Periodo");
        pnlTitGrid1.add(lblTitGrid1, cc.xy(3, 1));
        pnlResult1 = new JScrollPane();
        pnlGrid1.add(pnlResult1, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        tblGrid1 = new JTable();
        pnlResult1.setViewportView(tblGrid1);
        pnlGrid2.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:d:grow"));
        pnlMain.add(pnlGrid2, cc.xy(3, 7));
        pnlTitGrid2 = new JPanel();
        pnlTitGrid2.setLayout(new FormLayout("fill:16dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "center:d:noGrow"));
        pnlGrid2.add(pnlTitGrid2, cc.xy(1, 1));
        chkSel2 = new JCheckBox();
        chkSel2.setText("");
        pnlTitGrid2.add(chkSel2, cc.xy(1, 1));
        lblTitGrid2 = new JLabel();
        lblTitGrid2.setText("Margen de Venta en el Periodo");
        pnlTitGrid2.add(lblTitGrid2, cc.xy(3, 1));
        pnlResult2 = new JScrollPane();
        pnlGrid2.add(pnlResult2, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        tblGrid2 = new JTable();
        pnlResult2.setViewportView(tblGrid2);
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("right:d:grow", "fill:16dlu:noGrow"));
        pnlMain.add(footerPanel, cc.xyw(1, 9, 3));
        lblEsc = new JLabel();
        lblEsc.setText("Esc = Salir");
        footerPanel.add(lblEsc, cc.xy(1, 1));
        pnlGrid3 = new JPanel();
        pnlGrid3.setLayout(new FormLayout("fill:d:grow", "fill:d:grow,top:4dlu:noGrow,fill:d:grow"));
        pnlMain.add(pnlGrid3, cc.xy(1, 5));
        pnlTitGrid3 = new JPanel();
        pnlTitGrid3.setLayout(new FormLayout("fill:16dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:16dlu:noGrow"));
        pnlGrid3.add(pnlTitGrid3, cc.xy(1, 1));
        chkSel3 = new JCheckBox();
        chkSel3.setText("");
        pnlTitGrid3.add(chkSel3, cc.xy(1, 1));
        lblTitGrid3 = new JLabel();
        lblTitGrid3.setText("Ultimas 3 Ordenes de Compra");
        pnlTitGrid3.add(lblTitGrid3, cc.xy(3, 1));
        pnlResult3 = new JScrollPane();
        pnlGrid3.add(pnlResult3, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        tblGrid3 = new JTable();
        pnlResult3.setViewportView(tblGrid3);
        pnlGrid4 = new JPanel();
        pnlGrid4.setLayout(new FormLayout("fill:d:grow", "fill:16dlu:noGrow,top:4dlu:noGrow,center:d:grow"));
        pnlMain.add(pnlGrid4, cc.xy(3, 5));
        pnlTitGrid4 = new JPanel();
        pnlTitGrid4.setLayout(new FormLayout("fill:16dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:16dlu:noGrow"));
        pnlGrid4.add(pnlTitGrid4, cc.xy(1, 1));
        chkSel4 = new JCheckBox();
        chkSel4.setText("");
        pnlTitGrid4.add(chkSel4, cc.xy(1, 1));
        lblTitGrid4 = new JLabel();
        lblTitGrid4.setText("Cantidades Vendidas del Periodo");
        pnlTitGrid4.add(lblTitGrid4, cc.xy(3, 1));
        pnlResult4 = new JScrollPane();
        pnlGrid4.add(pnlResult4, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        tblGrid4 = new JTable();
        pnlResult4.setViewportView(tblGrid4);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
