package com.atux.desktop.inventario;

import com.aw.swing.mvp.ui.GradientPanel;
import com.aw.swing.mvp.ui.RoundedBorder;
import com.aw.swing.mvp.ui.RoundedPanel;
import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by JAVA on 15/11/2014.
 */
public class FrmKardex {
    public JPanel pnlForm;
    public JPanel pnlMain;
    public JTextField txtCoProducto;
    public JTextField txtDeProducto;
    public JLabel lblCoProducto;
    public JLabel lblDescripcion;
    public JPanel pnlGrid;
    public JPanel pnlTitGrid;
    public JLabel lblTitGrid;
    public JTextField txtLineaG1;
    public JTextField txtDivisionG2;
    public JTextField txtUnidadProducto;
    public JTextField txtDeLaboratorio;
    public JTextField txtVaFraccion;
    public JTextField txtStkEntero;
    public JTextField txtPrecioPromedio;
    public JTextField txtPrecioValorizado;
    public JTextField txtSubdivisionG3;
    public JTextField txtFamiliaG4;
    public JTextField txtSubFamiliaG5;
    public JLabel lblUnidad;
    public JLabel lblDeLaboratorio;
    public JLabel lblVaFraccion;
    public JLabel lblCantidad;
    public JLabel lblPrecioPromedio;
    public JLabel lblPrecioValorizado;
    public JLabel lblLineaG1;
    public JLabel lblDivisionG2;
    public JLabel lblSubdivisionG3;
    public JLabel lblFamiliaG4;
    public JLabel lblSubFamiliaG5;
    public JPanel footerPanel;
    public JLabel lblF3;
    public JLabel lblF5;
    public JCheckBox chkSel;
    public JTable tblGrid;
    public JScrollPane pnlResult;
    public JLabel lblEsc;
    public JTextField txtStkFraccion;

    private void createUIComponents() {
        pnlForm = new ZonePanel("Kardex", true);
        pnlGrid = new RoundedPanel(new BorderLayout(), 0);
        pnlGrid.setBorder(new RoundedBorder(0));
        footerPanel = new GradientPanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow", "fill:90dlu:noGrow,top:4dlu:noGrow,fill:160dlu:noGrow,top:4dlu:noGrow,fill:16dlu:noGrow"));
        pnlMain.setBackground(new Color(-986896));
        pnlMain.setMinimumSize(new Dimension(900, 450));
        pnlMain.setPreferredSize(new Dimension(1000, 450));
        pnlForm.setLayout(new FormLayout("fill:30dlu:noGrow,left:4dlu:noGrow,fill:d:noGrow,left:4dlu:noGrow,fill:80dlu:noGrow,left:4dlu:noGrow,fill:40dlu:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:30dlu:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:30dlu:noGrow,left:4dlu:noGrow,fill:30dlu:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:60dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,fill:4dlu:noGrow,fill:12dlu:noGrow"));
        pnlForm.setMinimumSize(new Dimension(902, 140));
        pnlForm.setPreferredSize(new Dimension(902, 140));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlForm, cc.xyw(1, 1, 2, CellConstraints.FILL, CellConstraints.FILL));
        txtDeProducto = new JTextField();
        pnlForm.add(txtDeProducto, cc.xyw(3, 3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblCoProducto = new JLabel();
        lblCoProducto.setText("Código");
        pnlForm.add(lblCoProducto, cc.xy(1, 1));
        txtCoProducto = new JTextField();
        pnlForm.add(txtCoProducto, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblDescripcion = new JLabel();
        lblDescripcion.setText("Descripción");
        pnlForm.add(lblDescripcion, cc.xy(3, 1));
        lblUnidad = new JLabel();
        lblUnidad.setText("Unidad");
        pnlForm.add(lblUnidad, cc.xy(7, 1));
        lblDeLaboratorio = new JLabel();
        lblDeLaboratorio.setText("Laboratorio");
        pnlForm.add(lblDeLaboratorio, cc.xy(9, 1));
        lblVaFraccion = new JLabel();
        lblVaFraccion.setText("Fracción");
        pnlForm.add(lblVaFraccion, cc.xy(13, 1));
        lblCantidad = new JLabel();
        lblCantidad.setText("Cant. Entero / Fracción");
        pnlForm.add(lblCantidad, cc.xyw(15, 1, 3));
        lblPrecioPromedio = new JLabel();
        lblPrecioPromedio.setText("Precio Prom.");
        pnlForm.add(lblPrecioPromedio, cc.xy(19, 1));
        lblPrecioValorizado = new JLabel();
        lblPrecioValorizado.setText("STK. Valorizado");
        pnlForm.add(lblPrecioValorizado, cc.xy(21, 1));
        lblLineaG1 = new JLabel();
        lblLineaG1.setText("Linea - G1");
        pnlForm.add(lblLineaG1, cc.xy(1, 5));
        txtLineaG1 = new JTextField();
        pnlForm.add(txtLineaG1, cc.xyw(1, 7, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblDivisionG2 = new JLabel();
        lblDivisionG2.setText("División - G2");
        pnlForm.add(lblDivisionG2, cc.xy(5, 5));
        txtDivisionG2 = new JTextField();
        pnlForm.add(txtDivisionG2, cc.xyw(5, 7, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblSubFamiliaG5 = new JLabel();
        lblSubFamiliaG5.setText("SubFamilia - G5");
        pnlForm.add(lblSubFamiliaG5, cc.xy(21, 5));
        lblSubdivisionG3 = new JLabel();
        lblSubdivisionG3.setText("SubDivisión - G3 ");
        pnlForm.add(lblSubdivisionG3, cc.xy(9, 5));
        txtUnidadProducto = new JTextField();
        pnlForm.add(txtUnidadProducto, cc.xy(7, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtDeLaboratorio = new JTextField();
        pnlForm.add(txtDeLaboratorio, cc.xyw(9, 3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtVaFraccion = new JTextField();
        pnlForm.add(txtVaFraccion, cc.xy(13, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtStkEntero = new JTextField();
        pnlForm.add(txtStkEntero, cc.xy(15, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtPrecioPromedio = new JTextField();
        pnlForm.add(txtPrecioPromedio, cc.xy(19, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtPrecioValorizado = new JTextField();
        pnlForm.add(txtPrecioValorizado, cc.xy(21, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtSubdivisionG3 = new JTextField();
        pnlForm.add(txtSubdivisionG3, cc.xyw(9, 7, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblFamiliaG4 = new JLabel();
        lblFamiliaG4.setText("Familia - G4");
        pnlForm.add(lblFamiliaG4, cc.xy(13, 5));
        txtFamiliaG4 = new JTextField();
        pnlForm.add(txtFamiliaG4, cc.xyw(13, 7, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtSubFamiliaG5 = new JTextField();
        pnlForm.add(txtSubFamiliaG5, cc.xy(21, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtStkFraccion = new JTextField();
        pnlForm.add(txtStkFraccion, cc.xy(17, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        pnlGrid = new JPanel();
        pnlGrid.setLayout(new FormLayout("fill:d:grow", "fill:16dlu:noGrow,top:4dlu:noGrow,fill:d:grow"));
        pnlGrid.setMinimumSize(new Dimension(454, 350));
        pnlGrid.setPreferredSize(new Dimension(453, 350));
        pnlMain.add(pnlGrid, cc.xyw(1, 3, 2, CellConstraints.DEFAULT, CellConstraints.FILL));
        pnlTitGrid = new JPanel();
        pnlTitGrid.setLayout(new FormLayout("fill:4dlu:noGrow,fill:16dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:16dlu:noGrow"));
        pnlTitGrid.setBackground(new Color(-986896));
        pnlGrid.add(pnlTitGrid, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        lblTitGrid = new JLabel();
        lblTitGrid.setText("Kardex - #feInicio#  al #feFin#");
        pnlTitGrid.add(lblTitGrid, cc.xy(4, 1));
        chkSel = new JCheckBox();
        chkSel.setText("");
        pnlTitGrid.add(chkSel, cc.xy(2, 1));
        pnlResult = new JScrollPane();
        pnlResult.setPreferredSize(new Dimension(453, 200));
        pnlGrid.add(pnlResult, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        tblGrid = new JTable();
        tblGrid.setPreferredScrollableViewportSize(new Dimension(450, 200));
        pnlResult.setViewportView(tblGrid);
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,right:max(d;4px):grow", "fill:16dlu:noGrow"));
        pnlMain.add(footerPanel, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.FILL));
        lblF3 = new JLabel();
        lblF3.setForeground(new Color(-16777216));
        lblF3.setText("F3 = Consultas");
        footerPanel.add(lblF3, cc.xy(1, 1));
        lblF5 = new JLabel();
        lblF5.setForeground(new Color(-16777216));
        lblF5.setText("F7 = Reporte");
        footerPanel.add(lblF5, cc.xy(3, 1));
        lblEsc = new JLabel();
        lblEsc.setText("Esc = Salir");
        footerPanel.add(lblEsc, cc.xy(5, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
