package com.aw.swing.mvp.navigation;

import com.aw.swing.context.SwingContext;
import com.aw.swing.mvp.ui.GradientPanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * User: User
 * Date: Nov 17, 2007
 */
public class FrmTab {
    public JPanel pnlMain;
    public JPanel pnlIconos;
    public JPanel pnlMensaje;
    public JLabel lblIcon;
    public JLabel lblMensaje;

    private void createUIComponents() {
        pnlMain = new GradientPanel();
        pnlIconos = new GradientPanel();
        pnlMensaje = new GradientPanel();
    }

    public static void main(String[] args) {
        try {
//            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingContext.initPLAF();
            FrmTab tab = new FrmTab();
            JDialog dlg = new JDialog(AWWindowsManager.instance().getFrame(), "", true);
            dlg.setSize(new Dimension(380, 130));
            dlg.getContentPane().setLayout(new BorderLayout());
            dlg.getContentPane().add(tab.pnlMain, BorderLayout.CENTER);
            dlg.setUndecorated(true);

//            dlg.getRootPane().setContentPane(tab.pnlMain);
            dlg.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:230dlu:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "fill:42dlu:noGrow,top:4dlu:noGrow,fill:21dlu:noGrow"));
        pnlMain.setBorder(BorderFactory.createTitledBorder(BorderFactory.createRaisedBevelBorder(), null));
        pnlIconos.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        pnlIconos.setMinimumSize(new Dimension(45, 45));
        pnlIconos.setPreferredSize(new Dimension(45, 45));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlIconos, cc.xy(3, 1));
        lblIcon = new JLabel();
        lblIcon.setAlignmentY(1.0f);
        lblIcon.setFont(new Font(lblIcon.getFont().getName(), Font.BOLD, 11));
        lblIcon.setForeground(new Color(-1));
        lblIcon.setMaximumSize(new Dimension(45, 45));
        lblIcon.setMinimumSize(new Dimension(45, 45));
        lblIcon.setPreferredSize(new Dimension(45, 45));
        lblIcon.setText("Icon");
        pnlIconos.add(lblIcon);
        pnlMensaje.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        pnlMensaje.setMinimumSize(new Dimension(45, 45));
        pnlMensaje.setPreferredSize(new Dimension(45, 45));
        pnlMain.add(pnlMensaje, cc.xy(3, 3));
        lblMensaje = new JLabel();
        lblMensaje.setFont(new Font(lblMensaje.getFont().getName(), Font.BOLD, 14));
        lblMensaje.setForeground(new Color(-1));
        lblMensaje.setMinimumSize(new Dimension(80, 20));
        lblMensaje.setPreferredSize(new Dimension(250, 20));
        lblMensaje.setText("Label");
        pnlMensaje.add(lblMensaje);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}