package com.atux.desktop.seguridad;

import com.aw.swing.mvp.ui.GradientPanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * User: User
 * Date: Nov 23, 2007
 */
public class FrmLogin {
    public JPanel pnlMain;
    public JTextField txtUserName;
    public JPasswordField txtPassword;

    public JLabel lblUserName;
    public JLabel lblPassword;
    public JPanel footerPanel;
    public JButton btnGrabar;
    public JButton btnCancel;
    public JButton btnAceptar;
    public String title = "Atux";
    public String description = "Ingrese Usuario";

    private void createUIComponents() {
        footerPanel = new GradientPanel();

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:0dlu:noGrow,fill:max(d;0px):noGrow,left:0dlu:grow,fill:28dlu:noGrow,left:10dlu:noGrow,fill:53dlu:noGrow,fill:11dlu:grow,fill:max(d;0dlu):noGrow", "center:7dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,center:max(d;0px):noGrow,center:max(d;14px):noGrow,fill:26dlu:noGrow,top:7dlu:noGrow"));
        pnlMain.setMinimumSize(new Dimension(240, 140));
        pnlMain.setPreferredSize(new Dimension(270, 170));
        lblUserName = new JLabel();
        lblUserName.setHorizontalAlignment(4);
        lblUserName.setText("Usuario");
        CellConstraints cc = new CellConstraints();
        pnlMain.add(lblUserName, cc.xy(4, 2));
        txtUserName = new JTextField();
        pnlMain.add(txtUserName, cc.xy(6, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblPassword = new JLabel();
        lblPassword.setHorizontalAlignment(4);
        lblPassword.setText("Clave");
        pnlMain.add(lblPassword, cc.xy(4, 4));
        txtPassword = new JPasswordField();
        pnlMain.add(txtPassword, cc.xy(6, 4, CellConstraints.FILL, CellConstraints.DEFAULT));
        footerPanel.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:55dlu:noGrow,left:4dlu:noGrow,fill:55dlu:noGrow,left:4dlu:noGrow,fill:max(d;0px):noGrow,left:d:grow,fill:max(d;0px):noGrow", "center:4dlu:noGrow,center:14dlu:noGrow,top:8dlu:noGrow"));
        footerPanel.setBackground(new Color(-8147749));
        footerPanel.setMinimumSize(new Dimension(12, 12));
        footerPanel.setPreferredSize(new Dimension(12, 12));
        pnlMain.add(footerPanel, cc.xyw(1, 8, 8));
        btnCancel = new JButton();
        btnCancel.setText("Cancelar");
        footerPanel.add(btnCancel, cc.xy(5, 2));
        btnAceptar = new JButton();
        btnAceptar.setText("Aceptar");
        footerPanel.add(btnAceptar, cc.xy(3, 2));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
