package com.aw.swing.mvp.ui.common;

import com.aw.swing.mvp.ui.MessageBlockerPanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * User: Juan Carlos Vergara
 * Date: 22-nov-2007
 * Time: 19:08:22
 */
public class FrmMessage {
    public JPanel pnlMain;
    public JProgressBar progressBar;
    public JLabel lblMensaje;
    public JLabel lblEspere;

    private void createUIComponents() {
        pnlMain = new MessageBlockerPanel();
        progressBar = new JProgressBar(0, 100);
        progressBar.setIndeterminate(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:10dlu:noGrow,top:4dlu:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow"));
        pnlMain.setAutoscrolls(true);
        pnlMain.setBackground(new Color(-16737895));
        pnlMain.setPreferredSize(new Dimension(400, 130));
        pnlMain.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        lblMensaje = new JLabel();
        lblMensaje.setBackground(new Color(-14010277));
        lblMensaje.setFont(new Font(lblMensaje.getFont().getName(), Font.BOLD, 18));
        lblMensaje.setForeground(new Color(-1));
        lblMensaje.setText("Procesando ...");
        lblMensaje.setVisible(false);
        CellConstraints cc = new CellConstraints();
        pnlMain.add(lblMensaje, cc.xy(3, 3));
        lblEspere = new JLabel();
        lblEspere.setFont(new Font(lblEspere.getFont().getName(), Font.BOLD, 12));
        lblEspere.setForeground(new Color(-1));
        lblEspere.setHorizontalAlignment(4);
        lblEspere.setText("Por favor espere unos momentos ...");
        lblEspere.setVisible(false);
        pnlMain.add(lblEspere, cc.xy(3, 7));
        pnlMain.add(progressBar, cc.xy(3, 6, CellConstraints.FILL, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
