/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ILaboratorio.java
 *
 * Created on 23/12/2014, 05:32:34 PM
 */
package atux.vistas.catalogo;
import atux.controllers.CLaboratorio;
import atux.modelgui.ModeloTablaLaboratorio;
import atux.util.ECampos;
import atux.util.FiltraEntrada;
import atux.util.Helper;
import atux.util.VerificadorEntrada;
import atux.util.common.AtuxVariables;
import atux.util.common.AtuxDBUtility;
import atux.util.common.AtuxUtility;
import atux.vistas.buscar.BuscarLaboratorio;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 *
 * @author Omar Davila
 */
public final class ILaboratorio extends javax.swing.JInternalFrame {
    private CLaboratorio cp;
    private ModeloTablaLaboratorio mtp;
    private boolean esActualizacion = false;
    private int tipoSeleccion = -1; //-1 todo,1 activos, 0 No activos
    public int finalPag = 0;//cont
    public int tmpFp = finalPag;
    public int inicioPag = 0;
    public int numRegistros = 0;
    private final Log logger = LogFactory.getLog(getClass());    
    /** Creates new form ILaboratorio */
    public ILaboratorio() {
        initComponents();
        
        cp = new CLaboratorio();
        mtp = new ModeloTablaLaboratorio(inicioPag,finalPag);
        numRegistros = mtp.getCantidadRegistros();

        tblLaboratorio.setModel(mtp);
        Helper.ajustarSoloAnchoColumnas(tblLaboratorio,ModeloTablaLaboratorio.anchoColumnas);
        setEventSelectionModel(tblLaboratorio.getSelectionModel());
        DesActivarCasillas();        
        setFiltroTexto();

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new elaprendiz.gui.panel.PanelImage();
        pnlEntradas = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblAbrevia = new javax.swing.JLabel();
        lblLaboratorio = new javax.swing.JLabel();
        lblDirec = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        lbleMaill = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        lblContacto = new javax.swing.JLabel();
        lblTelefonoContacto = new javax.swing.JLabel();
        lblMovil = new javax.swing.JLabel();
        lblEmailContacto = new javax.swing.JLabel();
        lblLabPropio = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtCodigo = new elaprendiz.gui.textField.TextField();
        txtAbreviatura = new elaprendiz.gui.textField.TextField();
        txtLaboratorio = new elaprendiz.gui.textField.TextField();
        txtDireccion = new elaprendiz.gui.textField.TextField();
        txtCiudad = new elaprendiz.gui.textField.TextField();
        txtEmailLaboratorio = new elaprendiz.gui.textField.TextField();
        txtTelefLaboratorio = new elaprendiz.gui.textField.TextField();
        txtFaxLaboratorio = new elaprendiz.gui.textField.TextField();
        txtContacto = new elaprendiz.gui.textField.TextField();
        txtTelefContacto = new elaprendiz.gui.textField.TextField();
        txtMovilContacto = new elaprendiz.gui.textField.TextField();
        txtEmailContacto = new elaprendiz.gui.textField.TextField();
        chbEstado = new javax.swing.JCheckBox();
        cmbLabPropio = new elaprendiz.gui.comboBox.ComboBoxRect();
        pnlBuscador = new javax.swing.JPanel();
        btnPrimero = new elaprendiz.gui.button.ButtonRect();
        btnAnterior = new elaprendiz.gui.button.ButtonRect();
        btnBuscar = new elaprendiz.gui.button.ButtonRect();
        btnSiguiente = new elaprendiz.gui.button.ButtonRect();
        btnUltimo = new elaprendiz.gui.button.ButtonRect();
        rbTodos = new javax.swing.JRadioButton();
        rbAtivos = new javax.swing.JRadioButton();
        rbNoActivos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaboratorio = new javax.swing.JTable();
        pnlAccionesLab = new javax.swing.JPanel();
        btnNuevo = new elaprendiz.gui.button.ButtonRect();
        btnModificar = new elaprendiz.gui.button.ButtonRect();
        btnGuardar = new elaprendiz.gui.button.ButtonRect();
        btnCancelar = new elaprendiz.gui.button.ButtonRect();
        btnSalir = new elaprendiz.gui.button.ButtonRect();
        bntParametrosReposicion = new elaprendiz.gui.button.ButtonRect();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Formulario de Laboratorios");

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atux/resources/fondoazulceleste.jpg"))); // NOI18N

        pnlEntradas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos de Laboratorio", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        pnlEntradas.setOpaque(false);
        pnlEntradas.setPreferredSize(new java.awt.Dimension(780, 200));

        lblCodigo.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblCodigo.setText("Codigo:");

        lblAbrevia.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblAbrevia.setText("Abrevia:");

        lblLaboratorio.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblLaboratorio.setText("Laboratorio:");

        lblDirec.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblDirec.setText("Direccion:");

        lblCiudad.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblCiudad.setText("Ciudad:");

        lbleMaill.setFont(new java.awt.Font("Tahoma", 1, 14));
        lbleMaill.setText("E-mail:");

        lblTelefono.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblTelefono.setText("Telefono:");

        lblFax.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblFax.setText("Fax:");

        lblContacto.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblContacto.setText("Contacto:");

        lblTelefonoContacto.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblTelefonoContacto.setText("Telefono:");

        lblMovil.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblMovil.setText("Movil:");

        lblEmailContacto.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblEmailContacto.setText("E-mail:");

        lblLabPropio.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblLabPropio.setText("Lab.Propio:");

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblEstado.setText("Estado:");

        txtCodigo.setEditable(false);
        txtCodigo.setDireccionDeSombra(30);
        txtCodigo.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtCodigo.setFont(new java.awt.Font("Arial", 0, 12));
        txtCodigo.setName(""); // NOI18N
        txtCodigo.setPreferredSize(new java.awt.Dimension(120, 25));
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });

        txtAbreviatura.setEditable(false);
        txtAbreviatura.setDireccionDeSombra(30);
        txtAbreviatura.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtAbreviatura.setFont(new java.awt.Font("Arial", 0, 12));
        txtAbreviatura.setPreferredSize(new java.awt.Dimension(120, 25));
        txtAbreviatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAbreviaturaKeyReleased(evt);
            }
        });

        txtLaboratorio.setEditable(false);
        txtLaboratorio.setDireccionDeSombra(30);
        txtLaboratorio.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtLaboratorio.setFont(new java.awt.Font("Arial", 0, 12));
        txtLaboratorio.setName("pruc"); // NOI18N
        txtLaboratorio.setPreferredSize(new java.awt.Dimension(120, 25));
        txtLaboratorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLaboratorioKeyReleased(evt);
            }
        });

        txtDireccion.setEditable(false);
        txtDireccion.setDireccionDeSombra(30);
        txtDireccion.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtDireccion.setFont(new java.awt.Font("Arial", 0, 12));
        txtDireccion.setPreferredSize(new java.awt.Dimension(120, 25));
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireccionKeyReleased(evt);
            }
        });

        txtCiudad.setEditable(false);
        txtCiudad.setDireccionDeSombra(30);
        txtCiudad.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtCiudad.setFont(new java.awt.Font("Arial", 0, 12));
        txtCiudad.setPreferredSize(new java.awt.Dimension(120, 25));
        txtCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCiudadKeyReleased(evt);
            }
        });

        txtEmailLaboratorio.setEditable(false);
        txtEmailLaboratorio.setDireccionDeSombra(30);
        txtEmailLaboratorio.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtEmailLaboratorio.setFont(new java.awt.Font("Arial", 0, 12));
        txtEmailLaboratorio.setInputVerifier(new VerificadorEntrada(125,VerificadorEntrada.EMAIL));
        txtEmailLaboratorio.setPreferredSize(new java.awt.Dimension(120, 25));
        txtEmailLaboratorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailLaboratorioKeyReleased(evt);
            }
        });

        txtTelefLaboratorio.setEditable(false);
        txtTelefLaboratorio.setDireccionDeSombra(30);
        txtTelefLaboratorio.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtTelefLaboratorio.setFont(new java.awt.Font("Arial", 0, 12));
        txtTelefLaboratorio.setPreferredSize(new java.awt.Dimension(120, 25));
        txtTelefLaboratorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefLaboratorioKeyReleased(evt);
            }
        });

        txtFaxLaboratorio.setEditable(false);
        txtFaxLaboratorio.setDireccionDeSombra(30);
        txtFaxLaboratorio.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtFaxLaboratorio.setFont(new java.awt.Font("Arial", 0, 12));
        txtFaxLaboratorio.setPreferredSize(new java.awt.Dimension(120, 25));
        txtFaxLaboratorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFaxLaboratorioKeyReleased(evt);
            }
        });

        txtContacto.setEditable(false);
        txtContacto.setDireccionDeSombra(30);
        txtContacto.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtContacto.setFont(new java.awt.Font("Arial", 0, 12));
        txtContacto.setPreferredSize(new java.awt.Dimension(120, 25));
        txtContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContactoKeyReleased(evt);
            }
        });

        txtTelefContacto.setEditable(false);
        txtTelefContacto.setDireccionDeSombra(30);
        txtTelefContacto.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtTelefContacto.setFont(new java.awt.Font("Arial", 0, 12));
        txtTelefContacto.setPreferredSize(new java.awt.Dimension(120, 25));
        txtTelefContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefContactoKeyReleased(evt);
            }
        });

        txtMovilContacto.setEditable(false);
        txtMovilContacto.setDireccionDeSombra(30);
        txtMovilContacto.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtMovilContacto.setFont(new java.awt.Font("Arial", 0, 12));
        txtMovilContacto.setPreferredSize(new java.awt.Dimension(120, 25));
        txtMovilContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMovilContactoKeyReleased(evt);
            }
        });

        txtEmailContacto.setEditable(false);
        txtEmailContacto.setDireccionDeSombra(30);
        txtEmailContacto.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtEmailContacto.setFont(new java.awt.Font("Arial", 0, 12));
        txtEmailContacto.setInputVerifier(new VerificadorEntrada(125,VerificadorEntrada.EMAIL));
        txtEmailContacto.setPreferredSize(new java.awt.Dimension(120, 25));
        txtEmailContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailContactoKeyReleased(evt);
            }
        });

        chbEstado.setBackground(new java.awt.Color(51, 153, 255));
        chbEstado.setFont(new java.awt.Font("Tahoma", 1, 14));
        chbEstado.setSelected(true);
        chbEstado.setText("Activo");
        chbEstado.setEnabled(false);
        chbEstado.setPreferredSize(new java.awt.Dimension(100, 25));
        chbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbEstadoActionPerformed(evt);
            }
        });
        chbEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chbEstadoKeyReleased(evt);
            }
        });

        cmbLabPropio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----------------", "Si", "No" }));
        cmbLabPropio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbLabPropioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlEntradasLayout = new javax.swing.GroupLayout(pnlEntradas);
        pnlEntradas.setLayout(pnlEntradasLayout);
        pnlEntradasLayout.setHorizontalGroup(
            pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCodigo)
                    .addComponent(lblDirec)
                    .addComponent(lbleMaill)
                    .addComponent(lblContacto)
                    .addComponent(lblEmailContacto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmailLaboratorio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addGroup(pnlEntradasLayout.createSequentialGroup()
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(lblAbrevia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAbreviatura, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlEntradasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailContacto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .addComponent(txtContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)))
                    .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEntradasLayout.createSequentialGroup()
                        .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTelefonoContacto)
                            .addComponent(lblLaboratorio)
                            .addComponent(lblCiudad)
                            .addComponent(lblTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .addGroup(pnlEntradasLayout.createSequentialGroup()
                                .addComponent(txtTelefLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(lblFax)
                                .addGap(18, 18, 18)
                                .addComponent(txtFaxLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEntradasLayout.createSequentialGroup()
                                .addComponent(txtTelefContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(lblMovil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMovilContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlEntradasLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblLabPropio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbLabPropio, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(lblEstado)
                        .addGap(18, 18, 18)
                        .addComponent(chbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlEntradasLayout.setVerticalGroup(
            pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEntradasLayout.createSequentialGroup()
                        .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFaxLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFax, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMovilContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                .addComponent(lblMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTelefContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblLabPropio)
                                .addComponent(cmbLabPropio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEstado))))
                    .addGroup(pnlEntradasLayout.createSequentialGroup()
                        .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAbreviatura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAbrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbleMaill, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pnlBuscador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        pnlBuscador.setOpaque(false);
        pnlBuscador.setPreferredSize(new java.awt.Dimension(780, 200));

        btnPrimero.setBackground(new java.awt.Color(102, 204, 0));
        btnPrimero.setText("<<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnAnterior.setBackground(new java.awt.Color(102, 204, 0));
        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(102, 204, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(102, 204, 0));
        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnUltimo.setBackground(new java.awt.Color(104, 204, 0));
        btnUltimo.setText(">>");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        rbTodos.setBackground(new java.awt.Color(51, 153, 255));
        rbTodos.setFont(new java.awt.Font("Arial", 1, 14));
        rbTodos.setForeground(new java.awt.Color(255, 255, 255));
        rbTodos.setText("Todos");
        rbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosActionPerformed(evt);
            }
        });

        rbAtivos.setBackground(new java.awt.Color(51, 153, 255));
        rbAtivos.setFont(new java.awt.Font("Arial", 1, 14));
        rbAtivos.setForeground(new java.awt.Color(255, 255, 255));
        rbAtivos.setText("Activos");
        rbAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAtivosActionPerformed(evt);
            }
        });

        rbNoActivos.setBackground(new java.awt.Color(51, 153, 255));
        rbNoActivos.setFont(new java.awt.Font("Arial", 1, 14));
        rbNoActivos.setForeground(new java.awt.Color(255, 255, 255));
        rbNoActivos.setText("No Activos");
        rbNoActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoActivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscadorLayout = new javax.swing.GroupLayout(pnlBuscador);
        pnlBuscador.setLayout(pnlBuscadorLayout);
        pnlBuscadorLayout.setHorizontalGroup(
            pnlBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
            .addGroup(pnlBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBuscadorLayout.createSequentialGroup()
                    .addGap(0, 9, Short.MAX_VALUE)
                    .addComponent(btnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)
                    .addComponent(rbTodos)
                    .addGap(5, 5, 5)
                    .addComponent(rbAtivos)
                    .addGap(5, 5, 5)
                    .addComponent(rbNoActivos)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );
        pnlBuscadorLayout.setVerticalGroup(
            pnlBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
            .addGroup(pnlBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBuscadorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(pnlBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbTodos)
                        .addComponent(rbAtivos)
                        .addComponent(rbNoActivos))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tblLaboratorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tblLaboratorio);

        pnlAccionesLab.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        pnlAccionesLab.setOpaque(false);
        pnlAccionesLab.setPreferredSize(new java.awt.Dimension(780, 200));

        btnNuevo.setBackground(new java.awt.Color(0, 153, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(51, 153, 255));
        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(51, 153, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(51, 153, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(51, 153, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccionesLabLayout = new javax.swing.GroupLayout(pnlAccionesLab);
        pnlAccionesLab.setLayout(pnlAccionesLabLayout);
        pnlAccionesLabLayout.setHorizontalGroup(
            pnlAccionesLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesLabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAccionesLabLayout.setVerticalGroup(
            pnlAccionesLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bntParametrosReposicion.setBackground(new java.awt.Color(0, 204, 0));
        bntParametrosReposicion.setText("*** REPOSICION");
        bntParametrosReposicion.setAlignmentX(0.1F);
        bntParametrosReposicion.setAlignmentY(0.1F);
        bntParametrosReposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntParametrosReposicionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(pnlBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bntParametrosReposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(pnlAccionesLab, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addComponent(pnlEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntParametrosReposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAccionesLab, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean guardarActualizar() throws SQLException{
        this.txtCodigo.setText(this.txtCodigo.getText().toUpperCase());
        this.txtAbreviatura.setText(this.txtAbreviatura.getText().toUpperCase());
        this.txtLaboratorio.setText(this.txtLaboratorio.getText().toUpperCase());
        this.txtCiudad.setText(this.txtCiudad.getText().toUpperCase());
        this.txtLaboratorio.setText(this.txtLaboratorio.getText().toUpperCase());
        this.txtDireccion.setText(this.txtDireccion.getText().toUpperCase());
        this.txtEmailLaboratorio.setText(this.txtEmailLaboratorio.getText().toUpperCase());
        this.txtEmailContacto.setText(this.txtEmailContacto.getText().toUpperCase());
        this.txtFaxLaboratorio.setText(this.txtFaxLaboratorio.getText().toUpperCase());
        this.txtTelefContacto.setText(this.txtTelefContacto.getText().toUpperCase());
        this.txtMovilContacto.setText(this.txtMovilContacto.getText().toUpperCase());
        this.txtTelefLaboratorio.setText(this.txtTelefLaboratorio.getText().toUpperCase());

        cp.getLaboratorio().setCoCompania(AtuxVariables.vCodigoCompania);
        cp.getLaboratorio().setCoLaboratorio(txtCodigo.getText());
        cp.getLaboratorio().setDeAbrevLab(txtAbreviatura.getText());
        cp.getLaboratorio().setDeLaboratorio(this.txtLaboratorio.getText());
        cp.getLaboratorio().setDeDirecLaboratorio(this.txtDireccion.getText());
        cp.getLaboratorio().setDeCiudad(this.txtCiudad.getText());
        cp.getLaboratorio().setNoEmailLab(this.txtEmailLaboratorio.getText());
        cp.getLaboratorio().setNuTelefLaboratorio(this.txtTelefLaboratorio.getText());
        cp.getLaboratorio().setNuFaxLaboratorio(this.txtFaxLaboratorio.getText());
        cp.getLaboratorio().setNoContacto(this.txtContacto.getText());
        cp.getLaboratorio().setNuTelContacto(this.txtTelefContacto.getText());
        cp.getLaboratorio().setNuMovilContacto(this.txtMovilContacto.getText());
        cp.getLaboratorio().setNoEmailContacto(this.txtEmailContacto.getText());
        cp.getLaboratorio().setInLabInventario("N");

        if (this.cmbLabPropio.getSelectedIndex()==1){
            cp.getLaboratorio().setInLabPropio("S");
        }else if(this.cmbLabPropio.getSelectedIndex()==2){
            cp.getLaboratorio().setInLabPropio("N");
        }else{
            cp.getLaboratorio().setInLabPropio(null);
        }
        if (chbEstado.isSelected()){
            cp.getLaboratorio().setEsLaboratorio("A");
        }else{
            cp.getLaboratorio().setEsLaboratorio("I");
        }
        
        Boolean EstadoGuardar=false;
            
        if(!esActualizacion){
            cp.getLaboratorio().setIdCreaLaboratorio(AtuxVariables.vIdUsuario);
            cp.getLaboratorio().setFeCreaLaboratorio(FormatoFecha(AtuxDBUtility.getFechaHoraBD(1)));
            cp.getLaboratorio().setCoLaboratorio(cp.getNuevoCodigoLaboratorio());
            txtCodigo.setText(cp.getLaboratorio().getCoLaboratorio());
            EstadoGuardar = cp.guardarRegistro(cp.getLaboratorio());
        }else{
            cp.getLaboratorio().setIdModLaboratorio(AtuxVariables.vIdUsuario);
            cp.getLaboratorio().setFeModLaboratorio(FormatoFecha(AtuxDBUtility.getFechaHoraBD(1)));
            int act = cp.actualizarRegistro(cp.getLaboratorio());
            if (act ==1) {
                EstadoGuardar = true;
            }
        }
        
        if(EstadoGuardar){
            EstadoGuardar = true; 
        }else{
            EstadoGuardar = false; 
        }
        return EstadoGuardar;
    }

    private Date FormatoFecha(String oldFecha){
        Date Fecha=null;
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String dateInString = oldFecha;

        try {
            Fecha = formatter.parse(dateInString);
        } catch (ParseException ex) {
            Logger.getLogger(ILaboratorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Fecha;
    }

    
    public void setFiltroTexto(){
        Helper.setFiltraEntrada(txtCodigo.getDocument(), FiltraEntrada.SOLO_NUMEROS, 6, false);
        Helper.setFiltraEntrada(txtAbreviatura.getDocument(), FiltraEntrada.NUM_LETRAS, 15, false);
        Helper.setFiltraEntrada(txtLaboratorio.getDocument(), FiltraEntrada.NUM_LETRAS, 60, true);
        Helper.setFiltraEntrada(txtDireccion.getDocument(), FiltraEntrada.NUM_LETRAS, 30, true); 
        Helper.setFiltraEntrada(txtContacto.getDocument(), FiltraEntrada.SOLO_LETRAS, 150, true);
        Helper.setFiltraEntrada(txtCiudad.getDocument(), FiltraEntrada.NUM_LETRAS, 100, true);
        Helper.setFiltraEntrada(txtTelefLaboratorio.getDocument(), FiltraEntrada.SOLO_NUMEROS, 20, false);
        Helper.setFiltraEntrada(txtFaxLaboratorio.getDocument(), FiltraEntrada.SOLO_NUMEROS, 20, false);
        Helper.setFiltraEntrada(txtTelefContacto.getDocument(), FiltraEntrada.SOLO_NUMEROS, 20, false);
        Helper.setFiltraEntrada(txtMovilContacto.getDocument(), FiltraEntrada.SOLO_NUMEROS, 20, false);
        Helper.setFiltraEntrada(txtEmailLaboratorio.getDocument(), FiltraEntrada.NUM_LETRAS, 100, false);
        Helper.setFiltraEntrada(txtEmailContacto.getDocument(), FiltraEntrada.NUM_LETRAS, 100, false);
    }    

    public boolean verficarCambios(){
        // TODO aguerra verificar     
        
        if(!this.txtCodigo.getText().equals(cp.getLaboratorio().getCoLaboratorio())){
            return true;
        }else if(!this.txtAbreviatura.getText().equals(cp.getLaboratorio().getDeAbrevLab())){
            return true;
        }else if(!this.txtLaboratorio.getText().equals(cp.getLaboratorio().getDeLaboratorio())){
            return true;
        }else if(!this.txtCiudad.getText().equals(cp.getLaboratorio().getDeCiudad())){
            return true;
        }else if(!this.txtContacto.getText().equals(cp.getLaboratorio().getNoContacto())){
            return true;
        }else if(!this.txtDireccion.getText().equals(cp.getLaboratorio().getDeDirecLaboratorio())){
            return true;
        }else if(!this.txtEmailLaboratorio.getText().equals(cp.getLaboratorio().getNoEmailLab())){
            return true;
        }else if(!this.txtEmailContacto.getText().equals(cp.getLaboratorio().getNoEmailContacto())){
            return true;
        }else if(!this.txtFaxLaboratorio.getText().equals(cp.getLaboratorio().getNuFaxLaboratorio())){
            return true;
        }else if(!this.txtTelefContacto.getText().equals(cp.getLaboratorio().getNuTelContacto())){
            return true;
        }else if(!this.txtMovilContacto.getText().equals(cp.getLaboratorio().getNuMovilContacto())){
            return true;
        }else if(!this.txtTelefLaboratorio.getText().equals(cp.getLaboratorio().getNuTelefLaboratorio())){
            return true;
        }else if(this.cmbLabPropio.getSelectedIndex()==1){
            if (!"L".equals(cp.getLaboratorio().getInLabPropio())){
                return true;
            }
        }else if(this.cmbLabPropio.getSelectedIndex()==2){
            if (!"D".equals(cp.getLaboratorio().getInLabPropio())){
                return true;
            }
        }else if(chbEstado.isSelected() != ("A".equals(cp.getLaboratorio().getEsLaboratorio()))){
            return true;
        }else if(!chbEstado.isSelected() != ("I".equals(cp.getLaboratorio().getEsLaboratorio()))){
            return true;
        }
        return false;
    }


    private void setEventSelectionModel(ListSelectionModel lsm){
        ListSelectionListener lsl = new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                selectionEvent(e);
            }
        };
        lsm.addListSelectionListener(lsl);
    }
    
    private void selectionEvent(ListSelectionEvent e){
        if(tblLaboratorio.getSelectedRow() != -1){
            numRegistros = tblLaboratorio.getSelectedRow();
            cp.setLaboratorio(mtp.getFila(tblLaboratorio.getSelectedRow()));
            setLaboratorio();     
            
        }
    }

    private void Limpiar(){
        this.txtCodigo.setText("");
        this.txtAbreviatura.setText("");
        this.txtLaboratorio.setText("");
        this.txtCiudad.setText("");
        this.txtContacto.setText("");
        this.txtDireccion.setText("");
        this.txtEmailLaboratorio.setText("");
        this.txtEmailContacto.setText("");
        this.txtFaxLaboratorio.setText("");
        this.txtTelefContacto.setText("");
        this.txtMovilContacto.setText("");
        this.txtTelefLaboratorio.setText("");
        this.cmbLabPropio.setSelectedIndex(0);
        chbSetActivo(false);
    }

    private void ActivarCasillas(){
//        if (esActualizacion == false) Limpiar();
        bntParametrosReposicion.setEnabled(false);
        pnlEntradas.setEnabled(false);
        this.tblLaboratorio.setEnabled(false);
        this.tblLaboratorio.clearSelection();        
        ECampos.setEditableTexto(this.pnlEntradas, true, new Component[]{lblCodigo,lblAbrevia,lblDirec,lbleMaill,lblContacto,lblEmailContacto,lblLaboratorio,lblCiudad,lblTelefono,lblTelefonoContacto,lblLabPropio,lblFax,lblMovil,lblEstado},false,"");
        this.btnNuevo.setEnabled(false);
        this.btnModificar.setEnabled(false);
        this.btnGuardar.setEnabled(true);
        this.btnCancelar.setEnabled(true);
        this.btnSalir.setEnabled(false);
        this.chbEstado.setEnabled(true);
        
        this.btnPrimero.setEnabled(false);
        this.btnUltimo.setEnabled(false);
        this.btnSiguiente.setEnabled(false);
        this.btnAnterior.setEnabled(false);
        this.btnBuscar.setEnabled(false);
        this.rbTodos.setEnabled(false);
        this.rbAtivos.setEnabled(false);
        this.rbNoActivos.setEnabled(false);
    }
    private void DesActivarCasillas(){
        this.pnlEntradas.setEnabled(true);

        ECampos.setEditableTexto(this.pnlEntradas, false, new Component[]{lblCodigo,lblAbrevia,lblDirec,lbleMaill,lblContacto,lblEmailContacto,lblLaboratorio,lblCiudad,lblTelefono,lblTelefonoContacto,lblLabPropio,lblFax,lblMovil,lblEstado},true,"");
        bntParametrosReposicion.setEnabled(true);
        this.tblLaboratorio.setEnabled(true);
        this.tblLaboratorio.clearSelection();
        this.btnNuevo.setEnabled(true);
        this.btnModificar.setEnabled(false);
        this.btnGuardar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.btnSalir.setEnabled(true);
        this.chbEstado.setEnabled(false);
        
        this.btnPrimero.setEnabled(true);
        this.btnUltimo.setEnabled(true);
        this.btnSiguiente.setEnabled(true);
        this.btnAnterior.setEnabled(true);
        this.btnBuscar.setEnabled(true);
        this.rbTodos.setEnabled(true);
        this.rbAtivos.setEnabled(true);
        this.rbNoActivos.setEnabled(true);        
        
        ECampos.esObligatorio(this.pnlEntradas,false);
        esActualizacion = false;
        this.pnlBuscador.setVisible(true);
        
        logger.info(txtCodigo.getText() + " - " + txtLaboratorio.getText());
    }

    public void chbSetActivo(boolean opcion){
        chbEstado.setSelected(true);
        chbEstado.setText("Activo");
        chbEstado.setBackground(new Color(104,204,0));
        chbEstado.setForeground(Color.BLACK);
        if(!opcion){
            chbEstado.setSelected(false);
            chbEstado.setText("No Activo");
            chbEstado.setBackground(Color.red);
            chbEstado.setForeground(Color.WHITE);
        }
    }

    private void setLaboratorio(){
        Limpiar();
        this.txtCodigo.setText(cp.getLaboratorio().getCoLaboratorio());
        this.txtAbreviatura.setText(cp.getLaboratorio().getDeAbrevLab());
        this.txtLaboratorio.setText(cp.getLaboratorio().getDeLaboratorio());
        this.txtCiudad.setText(cp.getLaboratorio().getDeCiudad());
        this.txtContacto.setText(cp.getLaboratorio().getNoContacto());
        this.txtDireccion.setText(cp.getLaboratorio().getDeDirecLaboratorio());
        this.txtEmailLaboratorio.setText(cp.getLaboratorio().getNoEmailLab());
        this.txtEmailContacto.setText(cp.getLaboratorio().getNoEmailContacto());
        this.txtFaxLaboratorio.setText(cp.getLaboratorio().getNuFaxLaboratorio());
        this.txtTelefContacto.setText(cp.getLaboratorio().getNuTelContacto());
        this.txtMovilContacto.setText(cp.getLaboratorio().getNuMovilContacto());
        this.txtTelefLaboratorio.setText(cp.getLaboratorio().getNuTelefLaboratorio());

        this.cmbLabPropio.setSelectedIndex(0);
        if ("S".equals(cp.getLaboratorio().getInLabPropio())){
            this.cmbLabPropio.setSelectedIndex(1);
        }else if ("N".equals(cp.getLaboratorio().getInLabPropio())){
            this.cmbLabPropio.setSelectedIndex(2);
        }

        if("A".equals(cp.getLaboratorio().getEsLaboratorio())){
            chbSetActivo(true); 
        }else{
            chbSetActivo(false); 
        }
        this.btnModificar.setEnabled(true);
    }
    
private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        finalPag = tblLaboratorio.getRowCount()-1;
        numRegistros=0;
        cp.setLaboratorio(mtp.getFila(numRegistros));
        setLaboratorio();           
        return;
}//GEN-LAST:event_btnPrimeroActionPerformed

private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        finalPag = tblLaboratorio.getRowCount() - 1;
        numRegistros = numRegistros - 1;
        if (numRegistros == -1){
            numRegistros=0;
        }
        cp.setLaboratorio(mtp.getFila(numRegistros));
        setLaboratorio();           

        return;
}//GEN-LAST:event_btnAnteriorActionPerformed

private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        BuscarLaboratorio Lab = new BuscarLaboratorio(tipoSeleccion);
        JLabel aviso = Lab.getAviso();
        String msj = (tipoSeleccion==-1?"Mostrando todos los Laboratorios existentes":(tipoSeleccion==1?"Mostrando todo los usuarios activos":"Mostrando todo los usuarios No activos"));
        JOptionPane.showInternalOptionDialog(this, Lab, msj,JOptionPane.OK_CANCEL_OPTION,
                                            JOptionPane.QUESTION_MESSAGE, null, new Object[]{aviso},null);

        if(Lab.getLaboratorio() != null){
           cp.setLaboratorio(Lab.getLaboratorio());
           setLaboratorio();
        }
}//GEN-LAST:event_btnBuscarActionPerformed

private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        finalPag = tblLaboratorio.getRowCount()-1;
        numRegistros = numRegistros + 1;
        if (finalPag < numRegistros){
            numRegistros=finalPag;
        }
        cp.setLaboratorio(mtp.getFila(numRegistros));
        setLaboratorio();           

        return;
}//GEN-LAST:event_btnSiguienteActionPerformed

private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        finalPag = tblLaboratorio.getRowCount()-1;
        numRegistros=finalPag;
        cp.setLaboratorio(mtp.getFila(numRegistros));
        setLaboratorio();           

        return;
}//GEN-LAST:event_btnUltimoActionPerformed

private void rbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosActionPerformed
        tipoSeleccion = -1;
        inicioPag = 0;  
        finalPag = tmpFp;
        mtp = new ModeloTablaLaboratorio(tipoSeleccion,inicioPag,finalPag);
        numRegistros = mtp.getCantidadRegistros();
        tblLaboratorio.setModel(mtp);
        Helper.ajustarSoloAnchoColumnas(tblLaboratorio,ModeloTablaLaboratorio.anchoColumnas);
        chbSetActivo(true);
}//GEN-LAST:event_rbTodosActionPerformed

private void rbAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAtivosActionPerformed
        tipoSeleccion = 1;
        inicioPag = 0; 
        finalPag = tmpFp;
        mtp = new ModeloTablaLaboratorio(tipoSeleccion,inicioPag,finalPag);
        numRegistros = mtp.getCantidadRegistros();
        tblLaboratorio.setModel(mtp);
        Helper.ajustarSoloAnchoColumnas(tblLaboratorio,ModeloTablaLaboratorio.anchoColumnas);
        chbSetActivo(true);
}//GEN-LAST:event_rbAtivosActionPerformed

private void rbNoActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoActivosActionPerformed
        tipoSeleccion = 0;
        inicioPag = 0; 
        finalPag = tmpFp;
        mtp = new ModeloTablaLaboratorio(tipoSeleccion,inicioPag,finalPag);
        numRegistros = mtp.getCantidadRegistros();
        tblLaboratorio.setModel(mtp);
        Helper.ajustarSoloAnchoColumnas(tblLaboratorio,ModeloTablaLaboratorio.anchoColumnas);
        chbSetActivo(false);
}//GEN-LAST:event_rbNoActivosActionPerformed

private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Limpiar();
        esActualizacion = false;        
        cp.getLaboratorio().setCoLaboratorio(cp.getNuevoCodigoLaboratorio());
    txtCodigo.setText(cp.getLaboratorio().getCoLaboratorio());
        txtAbreviatura.requestFocus();
        ActivarCasillas();       
}//GEN-LAST:event_btnNuevoActionPerformed

private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        esActualizacion = true;
        ActivarCasillas();
}//GEN-LAST:event_btnModificarActionPerformed

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (esActualizacion == false){
            txtCodigo.setText(cp.getNuevoCodigoLaboratorio());
        }

        if (JOptionPane.showConfirmDialog(this, "Esta Seguro de Guardar los Datos","Mensaje del Sistema",JOptionPane.YES_NO_OPTION)==JOptionPane.NO_OPTION){
            return;
        }
        if(ECampos.esObligatorio(this.pnlEntradas,true)){
            JOptionPane.showInternalMessageDialog(this, "Los campos en rojo son obligatorios", "Llene los campos obligatorios", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!this.verficarCambios()){
            if (JOptionPane.showConfirmDialog(this, "No se ha realizado ningun Cambio,\n Esta seguro de Continuar","Mensaje del Sistema",JOptionPane.YES_NO_OPTION)==JOptionPane.NO_OPTION){
                return;
            }            
        }
        
        boolean correcto = false; 

        if(!this.verficarCambios()){
            JOptionPane.showMessageDialog(this, "Debe cambiar por lo menos algun valor", "No hubo cambios", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try {
            correcto = guardarActualizar();
        } catch (SQLException ex) {
            Logger.getLogger(IProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
        if(!correcto){
            JOptionPane.showMessageDialog(this, "Error: no se pudo guardar.", "Error al guardar el registro", JOptionPane.ERROR_MESSAGE);
            ECampos.esObligatorio(this.pnlEntradas,false);
            return;
        }
        
        AtuxUtility.aceptarTransaccion();
        JOptionPane.showMessageDialog(this, "Información Guardada Satisfactoriamente", "Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);

        if(tipoSeleccion == -1){
            this.mtp = new ModeloTablaLaboratorio(inicioPag,finalPag);
        }else if(tipoSeleccion == 1){
            this.mtp = new ModeloTablaLaboratorio(tipoSeleccion,inicioPag,finalPag);
        }
        tblLaboratorio.setModel(mtp);
//        Helper.ajustarSoloAnchoColumnas(tblLaboratorio,ModeloTablaLaboratorio.anchoColumnas);
        this.numRegistros = mtp.getCantidadRegistros();
        Helper.ajustarSoloAnchoColumnas(tblLaboratorio,ModeloTablaLaboratorio.anchoColumnas);
        DesActivarCasillas();
        tblLaboratorio.requestFocus();
}//GEN-LAST:event_btnGuardarActionPerformed

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Se perderan todos los datos ingresados\nEsta Seguro de Cancelar ","Mensaje del Sistema",JOptionPane.YES_NO_OPTION)==JOptionPane.NO_OPTION){
            return;
        }

        DesActivarCasillas();
}//GEN-LAST:event_btnCancelarActionPerformed

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
    dispose();
}//GEN-LAST:event_btnSalirActionPerformed

private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
    switch (evt.getKeyCode()){
        case KeyEvent.VK_ENTER: txtAbreviatura.requestFocus();
             break;
    }    
}//GEN-LAST:event_txtCodigoKeyReleased

private void txtAbreviaturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbreviaturaKeyReleased
    switch (evt.getKeyCode()){
        case KeyEvent.VK_ENTER: txtLaboratorio.requestFocus();
             break;
    }    
}//GEN-LAST:event_txtAbreviaturaKeyReleased

private void txtLaboratorioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLaboratorioKeyReleased
    switch (evt.getKeyCode()){
        case KeyEvent.VK_ENTER: txtDireccion.requestFocus();
             break;
    }    
}//GEN-LAST:event_txtLaboratorioKeyReleased

private void txtDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyReleased
    switch (evt.getKeyCode()){
        case KeyEvent.VK_ENTER: txtCiudad.requestFocus();
             break;
    }    
}//GEN-LAST:event_txtDireccionKeyReleased

private void txtCiudadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiudadKeyReleased
    switch (evt.getKeyCode()){
        case KeyEvent.VK_ENTER: txtEmailLaboratorio.requestFocus();
             break;
    }    
}//GEN-LAST:event_txtCiudadKeyReleased

private void txtEmailLaboratorioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailLaboratorioKeyReleased
    switch (evt.getKeyCode()){
        case KeyEvent.VK_ENTER: txtTelefLaboratorio.requestFocus();
             break;
    }    
}//GEN-LAST:event_txtEmailLaboratorioKeyReleased

private void txtTelefLaboratorioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefLaboratorioKeyReleased
    switch (evt.getKeyCode()){
        case KeyEvent.VK_ENTER: txtFaxLaboratorio.requestFocus();
             break;
    }    
}//GEN-LAST:event_txtTelefLaboratorioKeyReleased

private void txtFaxLaboratorioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxLaboratorioKeyReleased
    switch (evt.getKeyCode()){
        case KeyEvent.VK_ENTER: txtContacto.requestFocus();
             break;
    }    
}//GEN-LAST:event_txtFaxLaboratorioKeyReleased

private void txtContactoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactoKeyReleased
    switch (evt.getKeyCode()){
        case KeyEvent.VK_ENTER: txtTelefContacto.requestFocus();
             break;
    }    
}//GEN-LAST:event_txtContactoKeyReleased

private void txtTelefContactoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefContactoKeyReleased
    switch (evt.getKeyCode()){
        case KeyEvent.VK_ENTER: txtMovilContacto.requestFocus();
             break;
    }    
}//GEN-LAST:event_txtTelefContactoKeyReleased

private void txtMovilContactoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMovilContactoKeyReleased
    switch (evt.getKeyCode()){
        case KeyEvent.VK_ENTER: txtEmailContacto.requestFocus();
             break;
    }    
}//GEN-LAST:event_txtMovilContactoKeyReleased

private void txtEmailContactoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailContactoKeyReleased
    switch (evt.getKeyCode()){
        case KeyEvent.VK_ENTER: cmbLabPropio.requestFocus();
             break;
    }    
}//GEN-LAST:event_txtEmailContactoKeyReleased

private void cmbLabPropioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbLabPropioKeyReleased
    switch (evt.getKeyCode()){
        case KeyEvent.VK_ENTER: chbEstado.requestFocus();
             break;
    }    
}//GEN-LAST:event_cmbLabPropioKeyReleased

private void chbEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chbEstadoKeyReleased
    switch (evt.getKeyCode()){
        case KeyEvent.VK_ENTER: btnGuardar.requestFocus();
             break;
    }    
}//GEN-LAST:event_chbEstadoKeyReleased

private void chbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbEstadoActionPerformed
        chbSetActivo(chbEstado.isSelected());
}//GEN-LAST:event_chbEstadoActionPerformed

private void bntParametrosReposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntParametrosReposicionActionPerformed
        IParamXReposicion pvc = new IParamXReposicion();
        pvc.setCodigoProducto(txtCodigo.getText());
        pvc.setDescripcionProducto(txtLaboratorio.getText());
        pvc.setTipoParametroReposicion("LB");
        pvc.CargaDatos();
        pvc.setPreferredSize(new Dimension(630, 480)); 
        
        //String msj = (tipoSeleccion==-1?"Mostrando todas las Especialidades del Medico":(tipoSeleccion==1?"Mostrando todo los usuarios activos":"Mostrando todo los usuarios No activos"));
        String msj = "Mostrando todas los Parametros de Reposición por Producto";
        JOptionPane.showInternalOptionDialog(this, pvc, msj,JOptionPane.OK_CANCEL_OPTION,
                                            -1, null, new Object[]{pvc.getAviso()},null);
}//GEN-LAST:event_bntParametrosReposicionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private elaprendiz.gui.button.ButtonRect bntParametrosReposicion;
    private elaprendiz.gui.button.ButtonRect btnAnterior;
    private elaprendiz.gui.button.ButtonRect btnBuscar;
    private elaprendiz.gui.button.ButtonRect btnCancelar;
    private elaprendiz.gui.button.ButtonRect btnGuardar;
    private elaprendiz.gui.button.ButtonRect btnModificar;
    private elaprendiz.gui.button.ButtonRect btnNuevo;
    private elaprendiz.gui.button.ButtonRect btnPrimero;
    private elaprendiz.gui.button.ButtonRect btnSalir;
    private elaprendiz.gui.button.ButtonRect btnSiguiente;
    private elaprendiz.gui.button.ButtonRect btnUltimo;
    private javax.swing.JCheckBox chbEstado;
    private elaprendiz.gui.comboBox.ComboBoxRect cmbLabPropio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAbrevia;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblContacto;
    private javax.swing.JLabel lblDirec;
    private javax.swing.JLabel lblEmailContacto;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblLabPropio;
    private javax.swing.JLabel lblLaboratorio;
    private javax.swing.JLabel lblMovil;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefonoContacto;
    private javax.swing.JLabel lbleMaill;
    private elaprendiz.gui.panel.PanelImage panelImage1;
    private javax.swing.JPanel pnlAccionesLab;
    private javax.swing.JPanel pnlBuscador;
    private javax.swing.JPanel pnlEntradas;
    private javax.swing.JRadioButton rbAtivos;
    private javax.swing.JRadioButton rbNoActivos;
    private javax.swing.JRadioButton rbTodos;
    private javax.swing.JTable tblLaboratorio;
    private elaprendiz.gui.textField.TextField txtAbreviatura;
    private elaprendiz.gui.textField.TextField txtCiudad;
    private elaprendiz.gui.textField.TextField txtCodigo;
    private elaprendiz.gui.textField.TextField txtContacto;
    private elaprendiz.gui.textField.TextField txtDireccion;
    private elaprendiz.gui.textField.TextField txtEmailContacto;
    private elaprendiz.gui.textField.TextField txtEmailLaboratorio;
    private elaprendiz.gui.textField.TextField txtFaxLaboratorio;
    private elaprendiz.gui.textField.TextField txtLaboratorio;
    private elaprendiz.gui.textField.TextField txtMovilContacto;
    private elaprendiz.gui.textField.TextField txtTelefContacto;
    private elaprendiz.gui.textField.TextField txtTelefLaboratorio;
    // End of variables declaration//GEN-END:variables
}
