/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package atux.vistas.catalogo;
import atux.controllers.CMedioControlAcceso;
import atux.managerbd.Mac;
import atux.util.ECampos;
import atux.util.FiltraEntrada;
import atux.util.Helper;
import atux.util.common.AtuxVariables;
import atux.util.common.AtuxUtility;
import atux.util.common.AtuxDBUtility;
import java.awt.Component;
import java.awt.Dialog.ModalExclusionType;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;


/**
 *
 *
 * @author Cesar Ruiz  PC
 */

public class ISerieValidacion extends javax.swing.JFrame {
//public class ISerieValidacion extends javax.swing.JInternalFrame {
    private CMedioControlAcceso cp;
    private String DireccionMAC;
    private String SerieHDD;
    public int finalPag = 0;//cont
    public int tmpFp = finalPag;
    public int inicioPag = 0;
    public int numRegistros = 0;
    public javax.swing.JFrame VentanaPrincipal;
    private final Log logger = LogFactory.getLog(getClass());    

        
        
    public ISerieValidacion(javax.swing.JFrame Ventana) {
        this.VentanaPrincipal= Ventana;
        initComponents();
        setLocationRelativeTo(null);
        setSize(620, 235);
        setAlwaysOnTop(true);
        VentanaPrincipal.setEnabled(false);
        cp = new CMedioControlAcceso();
        Series();
        setFiltroTexto();        
        Limpiar();
        ActivarCasillas();
    }

    private void setFiltroTexto(){
        Helper.setFiltraEntrada(txtRazonSocial.getDocument(), FiltraEntrada.NUM_LETRAS, 50, false);
        Helper.setFiltraEntrada(txtNumeroSerie.getDocument(), FiltraEntrada.SOLO_NUMEROS, 200, false);
        Helper.setFiltraEntrada(txtNumeroTerminal.getDocument(), FiltraEntrada.SOLO_NUMEROS, 2, false);
    }


    private void Series(){
        Mac mac = new Mac();
        DireccionMAC=mac.getMAC();
        SerieHDD=mac.getSerialNumberHDD();
    }

    private void Limpiar(){
        this.txtRazonSocial.setText("");
        this.txtNumeroSerie.setText("");
        this.txtNumeroTerminal.setText("");
    }

    private void ActivarCasillas(){
//        pnlEntradasTDeCambio.setEnabled(false);
        ECampos.setEditableTexto(this.pnlEntradasTDeCambio, true, new Component[]{lblRazonSocial,lblNumeroSerie,lblNumeroTerminales},true,"");        
        this.btnGuardar.setEnabled(true);
        this.btnCancelar.setEnabled(true);
    }

    private void DesActivarCasillas(){
        this.pnlEntradasTDeCambio.setEnabled(true);
        ECampos.setEditableTexto(this.pnlEntradasTDeCambio, false, new Component[]{lblRazonSocial,lblNumeroSerie,lblNumeroTerminales},true,"");        
        this.btnGuardar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
    }
    
    private boolean guardarActualizar() throws SQLException{
        Boolean EstadoGuardar=false;
        cp.getRegistroPorPk(new Object[]{DireccionMAC});

        if (cp.getMedioControlAcceso().getDeDireccionMAC() == null){
            cp.getMedioControlAcceso().setNuPc(Integer.parseInt(txtNumeroTerminal.getText()));
            cp.getMedioControlAcceso().setDeCodigoHDD(SerieHDD);
            cp.getMedioControlAcceso().setDeDireccionMAC(DireccionMAC);
            cp.getMedioControlAcceso().setFeCreaReg(FormatoFecha(AtuxDBUtility.getFechaHoraBD(1)));
            EstadoGuardar = cp.guardarRegistro(cp.getMedioControlAcceso());
        }

        if(EstadoGuardar){
            EstadoGuardar = true; 
        }else{
            EstadoGuardar = false; 
        }
        return EstadoGuardar;
    }
    
    private Date FormatoFecha(String oldFecha){
        Date Fecha=null;
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String dateInString = oldFecha;

        try {
            Fecha = formatter.parse(dateInString);
        } catch (ParseException ex) {
            Logger.getLogger(ISerieValidacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Fecha;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelImage1 = new elaprendiz.gui.panel.PanelImage();
        pnlEntradasTDeCambio = new javax.swing.JPanel();
        lblRazonSocial = new javax.swing.JLabel();
        txtRazonSocial = new elaprendiz.gui.textField.TextField();
        lblNumeroSerie = new javax.swing.JLabel();
        txtNumeroSerie = new elaprendiz.gui.textField.TextField();
        lblNumeroTerminales = new javax.swing.JLabel();
        txtNumeroTerminal = new elaprendiz.gui.textField.TextField();
        pnlAccionesTDeCambio = new javax.swing.JPanel();
        btnGuardar = new elaprendiz.gui.button.ButtonRect();
        btnCancelar = new elaprendiz.gui.button.ButtonRect();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Registro de Serie");
        setResizable(false);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atux/resources/fondoazulceleste.jpg"))); // NOI18N
        panelImage1.setPreferredSize(new java.awt.Dimension(500, 100));

        pnlEntradasTDeCambio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(0), "Ingreso de Numero de Serie de Registro", 1, 2));
        pnlEntradasTDeCambio.setOpaque(false);
        pnlEntradasTDeCambio.setPreferredSize(new java.awt.Dimension(748, 107));

        lblRazonSocial.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblRazonSocial.setText("Razon Social :");

        txtRazonSocial.setEditable(false);
        txtRazonSocial.setDireccionDeSombra(30);
        txtRazonSocial.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtRazonSocial.setFont(new java.awt.Font("Arial", 0, 12));
        txtRazonSocial.setName("pdescrip"); // NOI18N
        txtRazonSocial.setPreferredSize(new java.awt.Dimension(120, 25));

        lblNumeroSerie.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblNumeroSerie.setText("Número de Serie :");

        txtNumeroSerie.setEditable(false);
        txtNumeroSerie.setDireccionDeSombra(30);
        txtNumeroSerie.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtNumeroSerie.setFont(new java.awt.Font("Arial", 0, 12));
        txtNumeroSerie.setName("pdescrip"); // NOI18N
        txtNumeroSerie.setPreferredSize(new java.awt.Dimension(120, 25));

        lblNumeroTerminales.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblNumeroTerminales.setText("Número de Terminal :");

        txtNumeroTerminal.setEditable(false);
        txtNumeroTerminal.setDireccionDeSombra(30);
        txtNumeroTerminal.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtNumeroTerminal.setFont(new java.awt.Font("Arial", 0, 12));
        txtNumeroTerminal.setName("pdescrip"); // NOI18N
        txtNumeroTerminal.setPreferredSize(new java.awt.Dimension(120, 25));

        javax.swing.GroupLayout pnlEntradasTDeCambioLayout = new javax.swing.GroupLayout(pnlEntradasTDeCambio);
        pnlEntradasTDeCambio.setLayout(pnlEntradasTDeCambioLayout);
        pnlEntradasTDeCambioLayout.setHorizontalGroup(
            pnlEntradasTDeCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradasTDeCambioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEntradasTDeCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroSerie)
                    .addComponent(lblRazonSocial)
                    .addComponent(lblNumeroTerminales))
                .addGap(33, 33, 33)
                .addGroup(pnlEntradasTDeCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(txtNumeroSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(txtNumeroTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlEntradasTDeCambioLayout.setVerticalGroup(
            pnlEntradasTDeCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradasTDeCambioLayout.createSequentialGroup()
                .addGroup(pnlEntradasTDeCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEntradasTDeCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlEntradasTDeCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroTerminales, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAccionesTDeCambio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(0), "", 1, 2));
        pnlAccionesTDeCambio.setOpaque(false);
        pnlAccionesTDeCambio.setPreferredSize(new java.awt.Dimension(550, 50));

        btnGuardar.setBackground(new java.awt.Color(51, 153, 255));
        btnGuardar.setText("Aceptar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(51, 153, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccionesTDeCambioLayout = new javax.swing.GroupLayout(pnlAccionesTDeCambio);
        pnlAccionesTDeCambio.setLayout(pnlAccionesTDeCambioLayout);
        pnlAccionesTDeCambioLayout.setHorizontalGroup(
            pnlAccionesTDeCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesTDeCambioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlAccionesTDeCambioLayout.setVerticalGroup(
            pnlAccionesTDeCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, pnlAccionesTDeCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEntradasTDeCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(pnlAccionesTDeCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEntradasTDeCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAccionesTDeCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelImage1, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleName("Formulario Tipo de Cambio");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Esta Seguro de Guardar los Datos","Mensaje del Sistema",JOptionPane.YES_NO_OPTION)==JOptionPane.NO_OPTION){
            return;
        }

        Mac mac = new Mac();

        mac.getValidaSerie(this, txtRazonSocial.getText(), AtuxVariables.vCodigoLocal, txtNumeroSerie.getText(), Integer.parseInt(txtNumeroTerminal.getText()));
        if (mac.getStatusValidacion()==true){
            DireccionMAC=mac.getMAC();
            SerieHDD=mac.getSerialNumberHDD();
        }else{
            return;
        }
    
        boolean correcto =false;
        
        try {
            correcto = guardarActualizar();
        } catch (SQLException ex) {
            Logger.getLogger(IProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(!correcto){
            JOptionPane.showMessageDialog(this, "Error: no se pudo guardar.", "Error al guardar el registro", JOptionPane.ERROR_MESSAGE);
            ECampos.esObligatorio(this.pnlEntradasTDeCambio,false);
            return;
        }
        
        AtuxUtility.aceptarTransaccion();
        JOptionPane.showMessageDialog(this, "Información Guardada Satisfactoriamente", "Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);

        DesActivarCasillas();
        VentanaPrincipal.setEnabled(true);
        dispose();
}//GEN-LAST:event_btnGuardarActionPerformed

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    System.exit(0);    
    //dispose();
}//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private elaprendiz.gui.button.ButtonRect btnCancelar;
    private elaprendiz.gui.button.ButtonRect btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNumeroSerie;
    private javax.swing.JLabel lblNumeroTerminales;
    private javax.swing.JLabel lblRazonSocial;
    private elaprendiz.gui.panel.PanelImage panelImage1;
    private javax.swing.JPanel pnlAccionesTDeCambio;
    private javax.swing.JPanel pnlEntradasTDeCambio;
    private elaprendiz.gui.textField.TextField txtNumeroSerie;
    private elaprendiz.gui.textField.TextField txtNumeroTerminal;
    private elaprendiz.gui.textField.TextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables

  
}
