package com.atux.desktop.comun.auditoria;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * User: Kaiser
 * Date: 03/06/2009
 */
public class FrmAuditoriaInfo {
    public JPanel pnlMain;
    public JLabel lblTitCreacion;
    public JLabel lblTitModificacion;
    public JTextField txtUsuaCrea;
    public JTextField txtNoUsuCrea;
    public JTextField txtFechCrea;
    public JTextField txtUssoCrea;
    public JTextField txtNopcCrea;
    public JTextField txtUsuaModi;
    public JTextField txtNoUsuModi;
    public JTextField txtFechModi;
    public JTextField txtUssoModi;
    public JTextField txtNopcModi;
    public JTextField txtNuipCrea;
    public JTextField txtNuipModi;
    public JLabel lblUsuaCrea;
    public JLabel lblUsuaModi;
    public JLabel lblFechCrea;
    public JLabel lblUssoCrea;
    public JLabel lblNoPcCrea;
    public JLabel lblNuIpCrea;
    public JLabel lblFechModi;
    public JLabel lblUssoModi;
    public JLabel lblNoPcModi;
    public JLabel lblNuIPModi;
    public JPanel pnlToolBar;
    public JButton btnCancel;
    public JPanel pnlForm;
    public JPanel pnlForm1;
    public JTextField txtAnexoCrea;
    public JTextField txtAnexoModi;
    public JButton btnShowUserCrea;
    public JButton btnShowUserModi;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:d:grow,left:7dlu:noGrow,fill:d:grow", "fill:d:noGrow,top:4dlu:noGrow,center:14dlu:noGrow,fill:2dlu:noGrow,fill:d:grow"));
        pnlMain.setMinimumSize(new Dimension(590, 255));
        pnlMain.setPreferredSize(new Dimension(590, 287));
        pnlForm1 = new JPanel();
        pnlForm1.setLayout(new FormLayout("fill:d:noGrow,left:0dlu:noGrow,fill:d:grow,left:14dlu:noGrow,fill:max(d;0px):noGrow", "fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:0dlu:noGrow,center:d:noGrow"));
        pnlForm1.setMinimumSize(new Dimension(50, 168));
        pnlForm1.setPreferredSize(new Dimension(50, 168));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlForm1, cc.xy(1, 5));
        lblUsuaCrea = new JLabel();
        lblUsuaCrea.setText("Usuario");
        pnlForm1.add(lblUsuaCrea, cc.xy(1, 1));
        lblFechCrea = new JLabel();
        lblFechCrea.setText("Fecha");
        pnlForm1.add(lblFechCrea, cc.xy(1, 7));
        lblUssoCrea = new JLabel();
        lblUssoCrea.setText("Sistema Operativo");
        pnlForm1.add(lblUssoCrea, cc.xy(1, 9));
        lblNoPcCrea = new JLabel();
        lblNoPcCrea.setText("PC");
        pnlForm1.add(lblNoPcCrea, cc.xy(1, 11));
        lblNuIpCrea = new JLabel();
        lblNuIpCrea.setText("Número IP");
        pnlForm1.add(lblNuIpCrea, cc.xy(1, 13));
        txtUsuaCrea = new JTextField();
        pnlForm1.add(txtUsuaCrea, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtNoUsuCrea = new JTextField();
        pnlForm1.add(txtNoUsuCrea, cc.xyw(3, 3, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtFechCrea = new JTextField();
        pnlForm1.add(txtFechCrea, cc.xyw(3, 7, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtUssoCrea = new JTextField();
        pnlForm1.add(txtUssoCrea, cc.xyw(3, 9, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtNopcCrea = new JTextField();
        pnlForm1.add(txtNopcCrea, cc.xyw(3, 11, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtNuipCrea = new JTextField();
        pnlForm1.add(txtNuipCrea, cc.xyw(3, 13, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label1 = new JLabel();
        label1.setText("Anexo");
        pnlForm1.add(label1, cc.xy(1, 5));
        txtAnexoCrea = new JTextField();
        pnlForm1.add(txtAnexoCrea, cc.xyw(3, 5, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        btnShowUserCrea = new JButton();
        btnShowUserCrea.setBackground(new Color(-2103050));
        btnShowUserCrea.setIcon(new ImageIcon(getClass().getResource("/images/form-magnify.png")));
        btnShowUserCrea.setText("");
        pnlForm1.add(btnShowUserCrea, cc.xy(4, 1));
        pnlForm = new JPanel();
        pnlForm.setLayout(new FormLayout("fill:d:noGrow,left:0dlu:noGrow,fill:d:grow,left:14dlu:noGrow,fill:d:noGrow", "fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow"));
        pnlForm.setMinimumSize(new Dimension(50, 168));
        pnlForm.setPreferredSize(new Dimension(50, 168));
        pnlMain.add(pnlForm, cc.xy(3, 5));
        lblUsuaModi = new JLabel();
        lblUsuaModi.setText("Usuario");
        pnlForm.add(lblUsuaModi, cc.xy(1, 1));
        lblFechModi = new JLabel();
        lblFechModi.setText("Fecha");
        pnlForm.add(lblFechModi, cc.xy(1, 7));
        lblUssoModi = new JLabel();
        lblUssoModi.setText("Sistema Operativo");
        pnlForm.add(lblUssoModi, cc.xy(1, 9));
        lblNoPcModi = new JLabel();
        lblNoPcModi.setText("PC");
        pnlForm.add(lblNoPcModi, cc.xy(1, 11));
        lblNuIPModi = new JLabel();
        lblNuIPModi.setText("Número IP");
        pnlForm.add(lblNuIPModi, cc.xy(1, 13));
        txtUsuaModi = new JTextField();
        pnlForm.add(txtUsuaModi, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtNoUsuModi = new JTextField();
        pnlForm.add(txtNoUsuModi, cc.xyw(3, 3, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtFechModi = new JTextField();
        pnlForm.add(txtFechModi, cc.xyw(3, 7, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtUssoModi = new JTextField();
        pnlForm.add(txtUssoModi, cc.xyw(3, 9, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtNopcModi = new JTextField();
        pnlForm.add(txtNopcModi, cc.xyw(3, 11, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtNuipModi = new JTextField();
        pnlForm.add(txtNuipModi, cc.xyw(3, 13, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        label2.setText("Anexo");
        pnlForm.add(label2, cc.xy(1, 5));
        txtAnexoModi = new JTextField();
        pnlForm.add(txtAnexoModi, cc.xyw(3, 5, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        btnShowUserModi = new JButton();
        btnShowUserModi.setBackground(new Color(-2103050));
        btnShowUserModi.setIcon(new ImageIcon(getClass().getResource("/images/form-magnify.png")));
        btnShowUserModi.setText("");
        pnlForm.add(btnShowUserModi, cc.xy(4, 1));
        pnlToolBar = new JPanel();
        pnlToolBar.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:d:noGrow", "center:d:noGrow,fill:4dlu:noGrow,center:14dlu:noGrow,fill:4dlu:noGrow,center:d:noGrow"));
        pnlMain.add(pnlToolBar, cc.xyw(1, 1, 3));
        btnCancel = new JButton();
        btnCancel.setText("Cerrar");
        pnlToolBar.add(btnCancel, cc.xy(3, 3));
        lblTitCreacion = new JLabel();
        lblTitCreacion.setBackground(new Color(-8147749));
        lblTitCreacion.setFont(new Font(lblTitCreacion.getFont().getName(), Font.BOLD, 12));
        lblTitCreacion.setText("Creador");
        pnlMain.add(lblTitCreacion, cc.xy(1, 3));
        lblTitModificacion = new JLabel();
        lblTitModificacion.setBackground(new Color(-8147749));
        lblTitModificacion.setFont(new Font(lblTitModificacion.getFont().getName(), Font.BOLD, 12));
        lblTitModificacion.setText("Modificador");
        pnlMain.add(lblTitModificacion, cc.xy(3, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
