package com.atux.desktop.central;

import com.aw.swing.mvp.ui.GradientPanel;
import com.aw.swing.mvp.ui.RoundedBorder;
import com.aw.swing.mvp.ui.RoundedPanel;
import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by JAVA on 15/11/2014.
 */
public class FrmFraccionamiento {
    public JPanel pnlForm;
    public JPanel pnlMain;
    public JTextField txtCoProducto;
    public JTextField txtDeProducto;
    public JLabel lblCoProducto;
    public JLabel lblDescripcion;
    public JPanel pnlGrid;
    public JPanel pnlTitGrid;
    public JLabel lblTitGrid;

    public JTextField txtUnidadProducto;
    public JTextField txtDeLaboratorio;

    public JTextField txtMinFraccion;
    public JTextField txtCaEmpaqueMax;
    public JTextField txtCaEmpaqueMin;
    public JTextField txtMaxFraccion;
    public JLabel lblUnidad;
    public JLabel lblDeLaboratorio;
    public JLabel lblVaFraccion;
    public JLabel lblUnidadEmpaqueMin;
    public JLabel lblFamiliaG4;
    public JPanel footerPanel;
    public JLabel lblF3;
    public JCheckBox chkSel;
    public JTable tblGrid;
    public JScrollPane pnlResult;
    public JLabel lblEsc;
    public JLabel lblUnidadEmpaqueMax;
    public JLabel lblF10;

    private void createUIComponents() {
        pnlForm = new ZonePanel("Producto - Fraccionamiento", true);
        pnlGrid = new RoundedPanel(new BorderLayout(), 0);
        pnlGrid.setBorder(new RoundedBorder(0));
        footerPanel = new GradientPanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow", "fill:90dlu:noGrow,top:4dlu:noGrow,fill:160dlu:noGrow,top:4dlu:noGrow,fill:16dlu:noGrow"));
        pnlMain.setBackground(new Color(-986896));
        pnlMain.setMinimumSize(new Dimension(800, 450));
        pnlMain.setPreferredSize(new Dimension(1000, 450));
        pnlForm.setLayout(new FormLayout("fill:30dlu:noGrow,left:4dlu:noGrow,fill:d:noGrow,left:4dlu:noGrow,fill:100dlu:noGrow,left:4dlu:noGrow,fill:40dlu:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:40dlu:noGrow,left:4dlu:noGrow,fill:118px:noGrow,left:4dlu:noGrow,fill:119px:noGrow", "fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,fill:4dlu:noGrow,fill:12dlu:noGrow"));
        pnlForm.setMinimumSize(new Dimension(902, 140));
        pnlForm.setPreferredSize(new Dimension(902, 140));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlForm, cc.xyw(1, 1, 2, CellConstraints.FILL, CellConstraints.FILL));
        txtDeProducto = new JTextField();
        pnlForm.add(txtDeProducto, cc.xyw(3, 3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblCoProducto = new JLabel();
        lblCoProducto.setText("Código");
        pnlForm.add(lblCoProducto, cc.xy(1, 1));
        txtCoProducto = new JTextField();
        pnlForm.add(txtCoProducto, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblDescripcion = new JLabel();
        lblDescripcion.setText("Descripción");
        pnlForm.add(lblDescripcion, cc.xy(3, 1));
        lblUnidad = new JLabel();
        lblUnidad.setText("Unidad");
        pnlForm.add(lblUnidad, cc.xy(7, 1));
        lblDeLaboratorio = new JLabel();
        lblDeLaboratorio.setText("Laboratorio");
        pnlForm.add(lblDeLaboratorio, cc.xy(9, 1));
        lblVaFraccion = new JLabel();
        lblVaFraccion.setText("*Min Cant. Empaque");
        pnlForm.add(lblVaFraccion, cc.xy(13, 1));
        lblUnidadEmpaqueMin = new JLabel();
        lblUnidadEmpaqueMin.setText("Unidad Empaque");
        pnlForm.add(lblUnidadEmpaqueMin, cc.xy(15, 1));
        txtUnidadProducto = new JTextField();
        pnlForm.add(txtUnidadProducto, cc.xy(7, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtDeLaboratorio = new JTextField();
        pnlForm.add(txtDeLaboratorio, cc.xyw(9, 3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtCaEmpaqueMin = new JTextField();
        txtCaEmpaqueMin.setText("");
        pnlForm.add(txtCaEmpaqueMin, cc.xy(13, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtMinFraccion = new JTextField();
        pnlForm.add(txtMinFraccion, cc.xy(15, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblFamiliaG4 = new JLabel();
        lblFamiliaG4.setText("*Max Cant. Empaque");
        pnlForm.add(lblFamiliaG4, cc.xy(13, 5));
        txtCaEmpaqueMax = new JTextField();
        pnlForm.add(txtCaEmpaqueMax, cc.xy(13, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblUnidadEmpaqueMax = new JLabel();
        lblUnidadEmpaqueMax.setText("Unidad Empaque");
        pnlForm.add(lblUnidadEmpaqueMax, cc.xy(15, 5));
        txtMaxFraccion = new JTextField();
        pnlForm.add(txtMaxFraccion, cc.xy(15, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        pnlGrid = new JPanel();
        pnlGrid.setLayout(new FormLayout("fill:d:grow", "fill:16dlu:noGrow,top:4dlu:noGrow,fill:d:grow"));
        pnlGrid.setMinimumSize(new Dimension(454, 350));
        pnlGrid.setPreferredSize(new Dimension(453, 350));
        pnlMain.add(pnlGrid, cc.xyw(1, 3, 2, CellConstraints.DEFAULT, CellConstraints.FILL));
        pnlTitGrid = new JPanel();
        pnlTitGrid.setLayout(new FormLayout("fill:4dlu:noGrow,fill:16dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:16dlu:noGrow"));
        pnlTitGrid.setBackground(new Color(-986896));
        pnlGrid.add(pnlTitGrid, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        lblTitGrid = new JLabel();
        lblTitGrid.setText("Locales");
        pnlTitGrid.add(lblTitGrid, cc.xy(4, 1));
        chkSel = new JCheckBox();
        chkSel.setText("");
        pnlTitGrid.add(chkSel, cc.xy(2, 1));
        pnlResult = new JScrollPane();
        pnlResult.setPreferredSize(new Dimension(453, 200));
        pnlGrid.add(pnlResult, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        tblGrid = new JTable();
        tblGrid.setPreferredScrollableViewportSize(new Dimension(450, 200));
        pnlResult.setViewportView(tblGrid);
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,right:max(d;4px):grow", "fill:16dlu:noGrow"));
        pnlMain.add(footerPanel, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.FILL));
        lblF3 = new JLabel();
        lblF3.setForeground(new Color(-16777216));
        lblF3.setText("F2 = Modificar");
        footerPanel.add(lblF3, cc.xy(1, 1));
        lblEsc = new JLabel();
        lblEsc.setText("Esc = Salir");
        footerPanel.add(lblEsc, cc.xy(5, 1));
        lblF10 = new JLabel();
        lblF10.setText("F10 = Grabar");
        footerPanel.add(lblF10, cc.xy(3, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
