package com.atux.desktop.donacion;

import com.aw.swing.mvp.ui.RoundedBorder;
import com.aw.swing.mvp.ui.RoundedPanel;
import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by JAVA on 16/11/2014.
 */
public class FrmDonacion {
    public JPanel pnlMain;
    public JPanel pnlForm;
    public JPanel pnlGrid;
    public JTextField txtBuscar;
    public JLabel lblBuscar;
    public JPanel footerPanel;
    public JLabel lblEsc;
    public JTextField txtFeFin;
    public JTextField txtCoInstitucion;
    public JTextField txtDeInstitucion;
    public JTextField txtNoProveedor;
    public JLabel lblProveedor;
    public JTextField txtNuRucInstitucion;
    public JTextField txtDeDireccion;
    public JCheckBox chkEstado;
    public JLabel lblDeMensajeLargo;
    public JLabel lblObservacion;
    public JLabel lblEstado;
    public JTable tblGrid;
    public JCheckBox chkSel;
    public JScrollPane pnlResult;
    public JLabel lblTitGrid;
    public JPanel pnlTitGrid;
    public JTextField txtDeCortaInstitucion;
    public JTextField txtNuTelReferencia;
    public JTextField txtNuNroCuenta;
    public JTextField txtNoContacto;
    public JLabel lblNoContacto;
    public JLabel lblNuTelReferencia;
    public JLabel lblDeCortaInstitucion;
    public JLabel lblNuNroCuenta;

    private void createUIComponents() {
        pnlForm = new ZonePanel("Donacion", true);
        pnlGrid = new RoundedPanel(new BorderLayout(), 0);
        pnlGrid.setBorder(new RoundedBorder(0));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:d:grow", "fill:120dlu:noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,fill:16dlu:noGrow"));
        pnlMain.setMinimumSize(new Dimension(750, 435));
        pnlMain.setPreferredSize(new Dimension(750, 435));
        pnlForm.setLayout(new FormLayout("fill:50dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:10dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:40dlu:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow"));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlForm, cc.xy(1, 1));
        lblBuscar = new JLabel();
        lblBuscar.setText("Código ");
        pnlForm.add(lblBuscar, cc.xy(1, 1));
        txtCoInstitucion = new JTextField();
        pnlForm.add(txtCoInstitucion, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        chkEstado = new JCheckBox();
        chkEstado.setText("");
        pnlForm.add(chkEstado, cc.xy(15, 7));
        lblEstado = new JLabel();
        lblEstado.setText("Estado");
        pnlForm.add(lblEstado, cc.xy(13, 7));
        lblNuNroCuenta = new JLabel();
        lblNuNroCuenta.setText("N° Cuenta");
        pnlForm.add(lblNuNroCuenta, cc.xy(1, 9));
        txtNuNroCuenta = new JTextField();
        pnlForm.add(txtNuNroCuenta, cc.xyw(3, 9, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblProveedor = new JLabel();
        lblProveedor.setText("Institución");
        pnlForm.add(lblProveedor, cc.xy(7, 1));
        txtDeCortaInstitucion = new JTextField();
        pnlForm.add(txtDeCortaInstitucion, cc.xyw(3, 5, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtDeInstitucion = new JTextField();
        pnlForm.add(txtDeInstitucion, cc.xyw(7, 3, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblDeMensajeLargo = new JLabel();
        lblDeMensajeLargo.setText("RUC");
        pnlForm.add(lblDeMensajeLargo, cc.xy(3, 1));
        txtNuRucInstitucion = new JTextField();
        pnlForm.add(txtNuRucInstitucion, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblDeCortaInstitucion = new JLabel();
        lblDeCortaInstitucion.setText("Desc. Corta");
        pnlForm.add(lblDeCortaInstitucion, cc.xy(1, 5));
        lblNuTelReferencia = new JLabel();
        lblNuTelReferencia.setText("Teléfono");
        pnlForm.add(lblNuTelReferencia, cc.xy(9, 5));
        txtNuTelReferencia = new JTextField();
        pnlForm.add(txtNuTelReferencia, cc.xy(11, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblObservacion = new JLabel();
        lblObservacion.setText("Dirección");
        pnlForm.add(lblObservacion, cc.xy(1, 7));
        txtDeDireccion = new JTextField();
        pnlForm.add(txtDeDireccion, cc.xyw(3, 7, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblNoContacto = new JLabel();
        lblNoContacto.setText("Contacto");
        pnlForm.add(lblNoContacto, cc.xy(9, 9));
        txtNoContacto = new JTextField();
        pnlForm.add(txtNoContacto, cc.xyw(11, 9, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("right:d:grow", "fill:16dlu:noGrow"));
        pnlMain.add(footerPanel, cc.xy(1, 5));
        lblEsc = new JLabel();
        lblEsc.setText("Esc = Salir");
        footerPanel.add(lblEsc, cc.xy(1, 1));
        pnlGrid = new JPanel();
        pnlGrid.setLayout(new FormLayout("fill:612px:noGrow", "center:d:noGrow,top:4dlu:noGrow,center:d:grow"));
        pnlMain.add(pnlGrid, cc.xy(1, 3));
        pnlTitGrid = new JPanel();
        pnlTitGrid.setLayout(new FormLayout("fill:16dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:16dlu:noGrow"));
        pnlGrid.add(pnlTitGrid, cc.xy(1, 1));
        chkSel = new JCheckBox();
        chkSel.setText("");
        pnlTitGrid.add(chkSel, cc.xy(1, 1));
        lblTitGrid = new JLabel();
        lblTitGrid.setText("Locales");
        pnlTitGrid.add(lblTitGrid, cc.xy(3, 1));
        pnlResult = new JScrollPane();
        pnlGrid.add(pnlResult, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        tblGrid = new JTable();
        pnlResult.setViewportView(tblGrid);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
