package com.atux.desktop.consulta;

import com.aw.swing.mvp.ui.GradientPanel;
import com.aw.swing.mvp.ui.RoundedBorder;
import com.aw.swing.mvp.ui.RoundedPanel;
import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by JAVA on 17/11/2014.
 */
public class FrmDetalleVenta {
    public JPanel pnlMain;
    public JTable tblGrid;
    public JPanel pnlForm;
    public JPanel pnlGrid;
    public JTextField txtFeInicio;
    public JTextField txtFeFin;
    public JTextField txtVaPrecioPromedio;
    public JTextField txtVaTotal;
    public JTextField txtPorcentajeMargen;
    public JTextField txtPorcentajeUtilidad;
    public JTextField txtVaUtilidad;
    public JLabel lblFeInicio;
    public JLabel lblFeFin;
    public JLabel lblUtilidad;
    public JLabel lblPorcentajeUtilidad;
    public JScrollPane pnlResult;
    public JPanel pnlTitGrid;
    public JCheckBox chkSel;
    public JLabel lblTitGrid;
    public JPanel footerPanel;
    public JLabel lblF7;
    public JLabel lblEsc;
    public JLabel lblF6;
    public JLabel lblF5;
    public JLabel lblVaPrecioPromedio;
    public JLabel lblVaTotal;

    private void createUIComponents() {
        pnlForm = new ZonePanel("Detalle de Venta", true);
        pnlGrid = new RoundedPanel(new BorderLayout(), 0);
        pnlGrid.setBorder(new RoundedBorder(0));
        pnlTitGrid = new GradientPanel();
        footerPanel = new GradientPanel();

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:d:grow", "fill:d:noGrow,top:4dlu:noGrow,fill:d:grow,top:4dlu:noGrow,fill:16dlu:noGrow"));
        pnlMain.setMinimumSize(new Dimension(900, 456));
        pnlMain.setPreferredSize(new Dimension(900, 456));
        pnlForm.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:40dlu:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:40dlu:noGrow,left:4dlu:noGrow,fill:80dlu:noGrow,left:4dlu:noGrow,fill:40dlu:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:40dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow"));
        pnlForm.setMinimumSize(new Dimension(400, 85));
        pnlForm.setPreferredSize(new Dimension(400, 85));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlForm, cc.xy(1, 1));
        lblFeInicio = new JLabel();
        lblFeInicio.setText("Rango Evaluación");
        pnlForm.add(lblFeInicio, cc.xy(1, 1));
        txtFeInicio = new JTextField();
        txtFeInicio.setText("");
        pnlForm.add(txtFeInicio, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblFeFin = new JLabel();
        lblFeFin.setHorizontalAlignment(0);
        lblFeFin.setText("al");
        pnlForm.add(lblFeFin, cc.xy(5, 1, CellConstraints.FILL, CellConstraints.FILL));
        txtFeFin = new JTextField();
        pnlForm.add(txtFeFin, cc.xy(7, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblVaPrecioPromedio = new JLabel();
        lblVaPrecioPromedio.setText("Valor Precio Promedio S/.");
        pnlForm.add(lblVaPrecioPromedio, cc.xy(9, 1));
        txtVaPrecioPromedio = new JTextField();
        pnlForm.add(txtVaPrecioPromedio, cc.xy(11, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblVaTotal = new JLabel();
        lblVaTotal.setText("Vta. Total S/.");
        pnlForm.add(lblVaTotal, cc.xy(13, 1));
        txtVaTotal = new JTextField();
        pnlForm.add(txtVaTotal, cc.xy(15, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblUtilidad = new JLabel();
        lblUtilidad.setText("Utilidad S/.");
        pnlForm.add(lblUtilidad, cc.xy(13, 3));
        txtVaUtilidad = new JTextField();
        pnlForm.add(txtVaUtilidad, cc.xy(15, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtPorcentajeUtilidad = new JTextField();
        pnlForm.add(txtPorcentajeUtilidad, cc.xy(11, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblPorcentajeUtilidad = new JLabel();
        lblPorcentajeUtilidad.setText("% Utilidad");
        pnlForm.add(lblPorcentajeUtilidad, cc.xy(9, 3));
        pnlGrid.setLayout(new FormLayout("fill:d:grow", "fill:16dlu:noGrow,top:4dlu:noGrow,fill:d:grow"));
        pnlGrid.setMinimumSize(new Dimension(186, 336));
        pnlGrid.setPreferredSize(new Dimension(454, 336));
        pnlMain.add(pnlGrid, cc.xy(1, 3));
        pnlTitGrid = new JPanel();
        pnlTitGrid.setLayout(new FormLayout("fill:16dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:16dlu:noGrow"));
        pnlGrid.add(pnlTitGrid, cc.xy(1, 1));
        chkSel = new JCheckBox();
        chkSel.setText("");
        pnlTitGrid.add(chkSel, cc.xy(1, 1));
        lblTitGrid = new JLabel();
        lblTitGrid.setText("Relación de Productos Vendidos");
        pnlTitGrid.add(lblTitGrid, cc.xy(3, 1));
        pnlResult = new JScrollPane();
        pnlResult.setMinimumSize(new Dimension(23, 250));
        pnlResult.setPreferredSize(new Dimension(454, 250));
        pnlGrid.add(pnlResult, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        tblGrid = new JTable();
        pnlResult.setViewportView(tblGrid);
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:16dlu:noGrow"));
        pnlMain.add(footerPanel, cc.xy(1, 5));
        lblF7 = new JLabel();
        lblF7.setText("F7 = Reporte");
        footerPanel.add(lblF7, cc.xy(5, 1));
        lblEsc = new JLabel();
        lblEsc.setHorizontalAlignment(4);
        lblEsc.setText("ESC = Salir");
        footerPanel.add(lblEsc, cc.xy(7, 1));
        lblF6 = new JLabel();
        lblF6.setText("F6 = Filtrar");
        footerPanel.add(lblF6, cc.xy(3, 1));
        lblF5 = new JLabel();
        lblF5.setText("F5 = Ver Resumen");
        footerPanel.add(lblF5, cc.xy(1, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
