package com.atux.desktop.consulta;

import com.aw.swing.mvp.ui.RoundedBorder;
import com.aw.swing.mvp.ui.RoundedPanel;
import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by JAVA on 16/11/2014.
 */
public class FrmFNVentaVendedor {
    public JPanel pnlMain;
    public JPanel pnlForm;
    //    public JTextField txtBuscar;
    public JTable tblGrid;
    public JScrollPane pnlResult;
    public JPanel pnlGrid;
    public JPanel pnlTitGrid;
    public JCheckBox chkSel;
    public JLabel lblTitGrid;
    public JTextField txtBuscar;
    public JLabel lblVendedor;
    public JButton btnSearch;
    public JPanel footerPanel;
    public JLabel lblF2;
    public JLabel lblEsc;
    public JTextField txtFeInicio;
    public JTextField txtFeFin;
    public JLabel lblFeInicio;
    public JLabel lblFeFin;
    public JTextField txtVendedor;

    private void createUIComponents() {
        pnlForm = new ZonePanel("Detalle de Venta", true);
        pnlGrid = new RoundedPanel(new BorderLayout(), 0);
        pnlGrid.setBorder(new RoundedBorder(0));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:d:grow", "fill:58dlu:noGrow,top:4dlu:noGrow,fill:d:grow,top:4dlu:noGrow,fill:16dlu:noGrow"));
        pnlMain.setMinimumSize(new Dimension(900, 435));
        pnlMain.setPreferredSize(new Dimension(900, 435));
        pnlGrid.setLayout(new FormLayout("fill:d:grow", "fill:16dlu:noGrow,top:4dlu:noGrow,fill:d:grow"));
        pnlGrid.setPreferredSize(new Dimension(453, 465));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlGrid, cc.xy(1, 3));
        pnlTitGrid = new JPanel();
        pnlTitGrid.setLayout(new FormLayout("fill:16dlu:noGrow,left:4dlu:noGrow,fill:100dlu:noGrow", "fill:16dlu:noGrow"));
        pnlGrid.add(pnlTitGrid, cc.xy(1, 1));
        chkSel = new JCheckBox();
        chkSel.setText("");
        pnlTitGrid.add(chkSel, cc.xy(1, 1));
        lblTitGrid = new JLabel();
        lblTitGrid.setText("Lista de Ventas");
        pnlTitGrid.add(lblTitGrid, cc.xy(3, 1));
        pnlResult = new JScrollPane();
        pnlGrid.add(pnlResult, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        tblGrid = new JTable();
        tblGrid.setOpaque(true);
        pnlResult.setViewportView(tblGrid);
        pnlForm.setLayout(new FormLayout("fill:50dlu:noGrow,left:4dlu:noGrow,fill:150dlu:noGrow,left:4dlu:noGrow,fill:50dlu:noGrow,left:4dlu:noGrow,fill:40dlu:noGrow,left:4dlu:noGrow,fill:10dlu:noGrow,left:4dlu:noGrow,fill:40dlu:noGrow", "fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow"));
        pnlMain.add(pnlForm, cc.xy(1, 1));
        lblVendedor = new JLabel();
        lblVendedor.setText("Vendedor");
        pnlForm.add(lblVendedor, cc.xy(1, 1));
        txtFeInicio = new JTextField();
        pnlForm.add(txtFeInicio, cc.xy(7, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblFeInicio = new JLabel();
        lblFeInicio.setText("Rango de Fecha");
        pnlForm.add(lblFeInicio, cc.xy(5, 1));
        lblFeFin = new JLabel();
        lblFeFin.setHorizontalAlignment(0);
        lblFeFin.setText("al");
        pnlForm.add(lblFeFin, cc.xy(9, 1));
        txtFeFin = new JTextField();
        pnlForm.add(txtFeFin, cc.xy(11, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        btnSearch = new JButton();
        btnSearch.setText("Buscar");
        pnlForm.add(btnSearch, cc.xy(1, 3));
        txtVendedor = new JTextField();
        pnlForm.add(txtVendedor, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,right:max(d;4px):grow", "fill:16dlu:noGrow"));
        pnlMain.add(footerPanel, cc.xy(1, 5));
        lblF2 = new JLabel();
        lblF2.setText("F7 = Reporte");
        footerPanel.add(lblF2, cc.xy(1, 1));
        lblEsc = new JLabel();
        lblEsc.setText("Esc = Salir");
        footerPanel.add(lblEsc, cc.xy(3, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
