package com.atux.desktop.consulta;

import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import elaprendiz.gui.textField.TextField;

import javax.swing.*;
import java.awt.*;

/**
 * Created by MATRIX-JAVA on 20/11/2014.
 */
public class FrmSeleccionarRango {
    public JPanel pnlMain;
    public JTextField txtFeInicio;
    public JTextField txtFeFin;
    public JLabel lblFeFin;
    public JLabel lblFeInicio;
    public JPanel footerPanel;
    public JLabel lblF10;
    public JLabel lblEsc;
    public JPanel pnlForm;
    public JButton btnFeInicio;
    public JButton btnFeFin;

    private void createUIComponents() {
        txtFeInicio = new TextField();
        txtFeFin = new TextField();
        pnlForm = new ZonePanel("Seleccionar el rango de fechas", true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:d:grow", "fill:d:grow,top:4dlu:noGrow,fill:16dlu:noGrow"));
        pnlMain.setMinimumSize(new Dimension(360, 100));
        pnlMain.setPreferredSize(new Dimension(360, 100));
        pnlForm.setLayout(new FormLayout("fill:20dlu:noGrow,left:4dlu:noGrow,fill:45dlu:noGrow,left:4dlu:noGrow,left:10dlu:noGrow,left:4dlu:noGrow,center:10dlu:noGrow,left:4dlu:noGrow,fill:45dlu:noGrow,left:4dlu:noGrow,fill:10dlu:noGrow", "fill:12dlu:noGrow"));
        pnlForm.setMinimumSize(new Dimension(300, 70));
        pnlForm.setPreferredSize(new Dimension(300, 70));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlForm, cc.xy(1, 1));
        lblFeInicio = new JLabel();
        lblFeInicio.setText("Desde");
        lblFeInicio.setDisplayedMnemonic('D');
        lblFeInicio.setDisplayedMnemonicIndex(0);
        pnlForm.add(lblFeInicio, cc.xy(1, 1));
        txtFeInicio = new JTextField();
        pnlForm.add(txtFeInicio, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblFeFin = new JLabel();
        lblFeFin.setText("a");
        pnlForm.add(lblFeFin, cc.xy(7, 1));
        txtFeFin = new JTextField();
        pnlForm.add(txtFeFin, cc.xy(9, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        btnFeInicio = new JButton();
        btnFeInicio.setIcon(new ImageIcon(getClass().getResource("/images/cal-picker.png")));
        btnFeInicio.setText("");
        pnlForm.add(btnFeInicio, cc.xy(5, 1));
        btnFeFin = new JButton();
        btnFeFin.setIcon(new ImageIcon(getClass().getResource("/images/cal-picker.png")));
        btnFeFin.setText("");
        pnlForm.add(btnFeFin, cc.xy(11, 1));
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,right:d:grow", "fill:16dlu:noGrow"));
        pnlMain.add(footerPanel, cc.xy(1, 3));
        lblF10 = new JLabel();
        lblF10.setText("F10 = Aceptar");
        footerPanel.add(lblF10, cc.xy(1, 1));
        lblEsc = new JLabel();
        lblEsc.setText("Esc = Salir");
        footerPanel.add(lblEsc, cc.xy(3, 1));
        lblFeInicio.setLabelFor(txtFeInicio);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
