package com.atux.desktop.consulta;

import com.aw.swing.mvp.ui.RoundedBorder;
import com.aw.swing.mvp.ui.RoundedPanel;
import com.aw.swing.mvp.ui.ZonePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by MATRIX-JAVA on 18/11/2014.
 */
public class FrmVentaTransaccionResumen {
    public JPanel pnlMain;
    public JTextField txtFeInicio;
    public JTextField txtFeFin;
    public JTextField txtVaEmitido;
    public JTextField txtVaTicket;
    public JTextField txtVaFactura;
    public JTextField txtVaDevolucion;
    public JTextField txtVaTotal;
    public JPanel pnlForm;
    public JPanel pnlGrid;
    public JPanel pnlTitGrid;
    public JScrollPane pnlResult;
    public JTable tblGrid;
    public JCheckBox chkSel;
    public JLabel lblTitGrid;
    public JTextField txtVaOtro;
    public JLabel lblOtros;
    public JLabel lblTicket;
    public JLabel lblFactura;
    public JLabel lblDevolucion;
    public JLabel lblEmitido;
    public JLabel lblResumen;
    public JLabel lblA;
    public JTextField txtFormaPagoTotal;
    public JLabel lblFormaPagoTotal;
    public JPanel pnlFormaPagoTotal;
    public JLabel lblDocumentoTotal;
    public JTextField txtDocumentoTotal;
    public JPanel footerPanel;
    public JLabel lblEsc;

    private void createUIComponents() {
        pnlForm = new ZonePanel("Reporte Resumen", true);
        pnlGrid = new RoundedPanel(new BorderLayout(), 0);
        pnlGrid.setBorder(new RoundedBorder(0));
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlMain = new JPanel();
        pnlMain.setLayout(new FormLayout("fill:180dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "fill:d:grow,top:4dlu:noGrow,fill:16dlu:noGrow"));
        pnlMain.setMinimumSize(new Dimension(700, 310));
        pnlMain.setPreferredSize(new Dimension(700, 310));
        pnlForm.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:45dlu:noGrow,left:4dlu:noGrow,fill:10dlu:noGrow,left:4dlu:noGrow,fill:45dlu:noGrow", "fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:5dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow,top:4dlu:noGrow,fill:12dlu:noGrow"));
        pnlForm.setMinimumSize(new Dimension(100, 100));
        pnlForm.setPreferredSize(new Dimension(100, 100));
        CellConstraints cc = new CellConstraints();
        pnlMain.add(pnlForm, cc.xy(1, 1));
        lblResumen = new JLabel();
        lblResumen.setText("Resumen de Ventas ");
        pnlForm.add(lblResumen, cc.xy(1, 1));
        txtFeInicio = new JTextField();
        pnlForm.add(txtFeInicio, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblA = new JLabel();
        lblA.setText("a");
        pnlForm.add(lblA, cc.xy(5, 1));
        txtFeFin = new JTextField();
        pnlForm.add(txtFeFin, cc.xy(7, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblEmitido = new JLabel();
        lblEmitido.setText("Emitidos");
        pnlForm.add(lblEmitido, cc.xy(1, 3));
        txtVaEmitido = new JTextField();
        pnlForm.add(txtVaEmitido, cc.xyw(3, 3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblTicket = new JLabel();
        lblTicket.setText("Tickets");
        pnlForm.add(lblTicket, cc.xy(1, 5));
        lblFactura = new JLabel();
        lblFactura.setText("Facturas");
        pnlForm.add(lblFactura, cc.xy(1, 7));
        lblDevolucion = new JLabel();
        lblDevolucion.setText("Devolución");
        pnlForm.add(lblDevolucion, cc.xy(1, 9));
        txtVaTicket = new JTextField();
        pnlForm.add(txtVaTicket, cc.xyw(3, 5, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtVaFactura = new JTextField();
        pnlForm.add(txtVaFactura, cc.xyw(3, 7, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtVaDevolucion = new JTextField();
        pnlForm.add(txtVaDevolucion, cc.xyw(3, 9, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtVaTotal = new JTextField();
        pnlForm.add(txtVaTotal, cc.xyw(3, 13, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblOtros = new JLabel();
        lblOtros.setText("Otros");
        pnlForm.add(lblOtros, cc.xy(1, 11));
        txtVaOtro = new JTextField();
        pnlForm.add(txtVaOtro, cc.xyw(3, 11, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblDocumentoTotal = new JLabel();
        lblDocumentoTotal.setText("Totales");
        pnlForm.add(lblDocumentoTotal, cc.xy(1, 15));
        txtDocumentoTotal = new JTextField();
        pnlForm.add(txtDocumentoTotal, cc.xyw(3, 15, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        pnlGrid.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,fill:d:grow,top:4dlu:noGrow,fill:12dlu:noGrow"));
        pnlGrid.setPreferredSize(new Dimension(253, 89));
        pnlMain.add(pnlGrid, cc.xy(3, 1));
        pnlTitGrid = new JPanel();
        pnlTitGrid.setLayout(new FormLayout("fill:16dlu:noGrow,left:4dlu:noGrow,fill:d:grow", "center:16dlu:noGrow"));
        pnlGrid.add(pnlTitGrid, cc.xy(1, 1));
        chkSel = new JCheckBox();
        chkSel.setText("");
        pnlTitGrid.add(chkSel, cc.xy(1, 1));
        lblTitGrid = new JLabel();
        lblTitGrid.setText("Forma de pagos");
        pnlTitGrid.add(lblTitGrid, cc.xy(3, 1));
        pnlResult = new JScrollPane();
        pnlResult.setPreferredSize(new Dimension(53, 19));
        pnlGrid.add(pnlResult, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        tblGrid = new JTable();
        pnlResult.setViewportView(tblGrid);
        pnlFormaPagoTotal = new JPanel();
        pnlFormaPagoTotal.setLayout(new FormLayout("right:max(d;4px):grow,left:4dlu:noGrow,right:50dlu:noGrow", "fill:12dlu:noGrow"));
        pnlGrid.add(pnlFormaPagoTotal, cc.xy(1, 5));
        txtFormaPagoTotal = new JTextField();
        pnlFormaPagoTotal.add(txtFormaPagoTotal, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblFormaPagoTotal = new JLabel();
        lblFormaPagoTotal.setText("Totales");
        pnlFormaPagoTotal.add(lblFormaPagoTotal, cc.xy(1, 1));
        footerPanel = new JPanel();
        footerPanel.setLayout(new FormLayout("fill:d:grow", "fill:16dlu:noGrow"));
        pnlMain.add(footerPanel, cc.xyw(1, 3, 3));
        lblEsc = new JLabel();
        lblEsc.setText("Esc = Salir");
        footerPanel.add(lblEsc, cc.xy(1, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
