CREATE TABLE COMUN.CMTS_PARAMETRO
(
  CO_PARAMETRO CHAR(3) NOT NULL ,
  DE_PARAMETRO CHAR(250) NULL, 
  IN_ACTIVO CHAR(1) DEFAULT 'S' NOT NULL 
, CONSTRAINT CMTS_PARAMETRO_PK PRIMARY KEY 
  (
    CO_PARAMETRO 
  )
  ENABLE 
) ;

GRANT SELECT, INSERT, UPDATE, DELETE ON COMUN.CMTS_PARAMETRO TO ECVENTA;


CREATE PUBLIC SYNONYM CMTS_PARAMETRO 
   FOR COMUN.CMTS_PARAMETRO ;