/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IAsignacionCajeroCaja.java
 *
 * Created on 19/12/2014, 05:54:03 PM
 */
package atux.vistas;

/**
 *
 * @author user
 */
public class IAsignacionCajeroCaja extends javax.swing.JDialog {

    /** Creates new form IAsignacionCajeroCaja */
    public IAsignacionCajeroCaja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImageAsignacionCajero = new elaprendiz.gui.panel.PanelImage();
        jScrollPaneRelCajas = new javax.swing.JScrollPane();
        tblCajas = new javax.swing.JTable();
        lblCaja = new javax.swing.JLabel();
        lblCajero = new javax.swing.JLabel();
        bntSalir = new elaprendiz.gui.button.ButtonRect();
        bntAgregar = new elaprendiz.gui.button.ButtonRect();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelImageAsignacionCajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atux/resources/fondoazulceleste.jpg"))); // NOI18N

        tblCajas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Sel", "Secuencial", "Nombres"
            }
        ));
        jScrollPaneRelCajas.setViewportView(tblCajas);

        lblCaja.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblCaja.setForeground(new java.awt.Color(255, 255, 255));
        lblCaja.setText("Asignado a:");

        lblCajero.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblCajero.setForeground(new java.awt.Color(255, 255, 0));
        lblCajero.setText("User01");

        bntSalir.setBackground(new java.awt.Color(51, 153, 255));
        bntSalir.setText("Salir");
        bntSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalirActionPerformed(evt);
            }
        });

        bntAgregar.setBackground(new java.awt.Color(51, 153, 255));
        bntAgregar.setText("Agregar");

        javax.swing.GroupLayout panelImageAsignacionCajeroLayout = new javax.swing.GroupLayout(panelImageAsignacionCajero);
        panelImageAsignacionCajero.setLayout(panelImageAsignacionCajeroLayout);
        panelImageAsignacionCajeroLayout.setHorizontalGroup(
            panelImageAsignacionCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImageAsignacionCajeroLayout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(bntAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(panelImageAsignacionCajeroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(panelImageAsignacionCajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneRelCajas, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelImageAsignacionCajeroLayout.setVerticalGroup(
            panelImageAsignacionCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageAsignacionCajeroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPaneRelCajas, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addGroup(panelImageAsignacionCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(panelImageAsignacionCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImageAsignacionCajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImageAsignacionCajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalirActionPerformed

        this.dispose();     }//GEN-LAST:event_bntSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private elaprendiz.gui.button.ButtonRect bntAgregar;
    private elaprendiz.gui.button.ButtonRect bntSalir;
    private javax.swing.JScrollPane jScrollPaneRelCajas;
    private javax.swing.JLabel lblCaja;
    private javax.swing.JLabel lblCajero;
    private elaprendiz.gui.panel.PanelImage panelImageAsignacionCajero;
    private javax.swing.JTable tblCajas;
    // End of variables declaration//GEN-END:variables
}
