package atux.vistas.venta;

import atux.modelbd.ProductoLocal;
import atux.util.common.AtuxSearch;
import atux.util.common.AtuxUtility;
import atux.util.common.AtuxVariables;
import javax.swing.*;
import java.awt.event.KeyEvent;
import java.sql.SQLException;

/**
 *
 * @author user
 */
public class IProductoFaltaCero extends javax.swing.JDialog {

    ProductoLocal prodLocal;
    JDialog parent;

    public IProductoFaltaCero(JDialog parent, boolean modal,ProductoLocal productoLocal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Registro Falta Cero");
        this.parent = parent;
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        AtuxUtility.centrarVentana(this);
        this.prodLocal = productoLocal;
        txtUnidad.setText(productoLocal.getDeUnidadFraccion());
        txtCantidad.setText("1");
        AtuxUtility.moveFocus(txtCantidad);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagenProductoFaltaCero = new elaprendiz.gui.panel.PanelImage();
        btnSalir = new elaprendiz.gui.button.ButtonRect();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new elaprendiz.gui.textField.TextField();
        btnAceptar = new javax.swing.JButton();
        txtUnidad = new elaprendiz.gui.textField.TextField();
        lblUnidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelImagenProductoFaltaCero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atux/resources/fondoazulceleste.jpg"))); // NOI18N

        btnSalir.setBackground(new java.awt.Color(51, 153, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblCantidad.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblCantidad.setText("Cantidad");

        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad.setPreferredSize(new java.awt.Dimension(615, 22));
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(204, 204, 255));
        btnAceptar.setForeground(new java.awt.Color(0, 0, 51));
        btnAceptar.setMnemonic('A');
        btnAceptar.setText("Aceptar");
        btnAceptar.setToolTipText("Buscar Pedido");
        btnAceptar.setPreferredSize(new java.awt.Dimension(28, 20));
        btnAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/atux/resources/search32select.png"))); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        txtUnidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUnidad.setPreferredSize(new java.awt.Dimension(615, 22));

        lblUnidad.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblUnidad.setText("Unidad");

        javax.swing.GroupLayout panelImagenProductoFaltaCeroLayout = new javax.swing.GroupLayout(panelImagenProductoFaltaCero);
        panelImagenProductoFaltaCero.setLayout(panelImagenProductoFaltaCeroLayout);
        panelImagenProductoFaltaCeroLayout.setHorizontalGroup(
            panelImagenProductoFaltaCeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagenProductoFaltaCeroLayout.createSequentialGroup()
                .addGroup(panelImagenProductoFaltaCeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImagenProductoFaltaCeroLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImagenProductoFaltaCeroLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImagenProductoFaltaCeroLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        panelImagenProductoFaltaCeroLayout.setVerticalGroup(
            panelImagenProductoFaltaCeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagenProductoFaltaCeroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelImagenProductoFaltaCeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelImagenProductoFaltaCeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblUnidad.getAccessibleContext().setAccessibleName("Unidad de venta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagenProductoFaltaCero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagenProductoFaltaCero, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       closeWindow(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Desea colocar al producto " + prodLocal.getProducto().getDeProducto() + "\n" + " como falta CERO", "Mensaje del Sistema", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            int cant = Integer.parseInt(txtCantidad.getText());
            try {
                AtuxSearch.updateProdNoAtendido(prodLocal,cant);
            } catch (SQLException e) {
                e.printStackTrace();
            }
            btnSalir.doClick();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAceptar.doClick();
        }
    }//GEN-LAST:event_txtCantidadKeyPressed

    public void closeWindow(boolean pAceptar) {
        AtuxVariables.vAceptar = pAceptar;
        this.setVisible(false);
        this.dispose();
        parent.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private elaprendiz.gui.button.ButtonRect btnSalir;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblUnidad;
    private elaprendiz.gui.panel.PanelImage panelImagenProductoFaltaCero;
    private elaprendiz.gui.textField.TextField txtCantidad;
    private elaprendiz.gui.textField.TextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
